Repository OCA/server-auth, pull requests merged in 2019-03, with the labels that each got.

#76 [FIX] Monkeypatch TestCursor in auth_brute_force's tests
  auth_brute_force/tests/test_brute_force.py
Labels: approved

#74 [11.0][IMP] Show the secret code in the authenticator
  auth_totp/__manifest__.py
  auth_totp/wizards/res_users_authenticator_create.py
  auth_totp/wizards/res_users_authenticator_create.xml
Labels: approved, ready to merge

#72 [ADD] Add module for authentication with U2F
  auth_u2f/LICENSE.txt
  auth_u2f/__init__.py
  auth_u2f/__manifest__.py
  auth_u2f/controllers/__init__.py
  auth_u2f/controllers/main.py
  auth_u2f/i18n/auth_u2f.pot
  auth_u2f/models/__init__.py
  auth_u2f/models/http.py
  auth_u2f/models/res_users.py
  auth_u2f/models/u2f_device.py
  auth_u2f/readme/DESCRIPTION.rst
  auth_u2f/readme/INSTALL.rst
  auth_u2f/readme/USAGE.rst
  auth_u2f/security/auth_u2f_security.xml
  auth_u2f/security/ir.model.access.csv
  auth_u2f/static/src/js/auth_u2f.js
  auth_u2f/static/src/js/auth_u2f_frontend.js
  auth_u2f/tests/__init__.py
  auth_u2f/tests/test_device.py
  auth_u2f/tests/test_http.py
  auth_u2f/tests/test_main.py
  auth_u2f/tests/test_users.py
  auth_u2f/views/res_users.xml
  auth_u2f/views/u2f_device.xml
  auth_u2f/views/u2f_templates.xml
  requirements.txt
Labels: needs review

#77 [12.0][ADD] base_user_show_email
  base_user_show_email/README.rst
  base_user_show_email/__init__.py
  base_user_show_email/__manifest__.py
  base_user_show_email/readme/CONTRIBUTORS.rst
  base_user_show_email/readme/DESCRIPTION.rst
  base_user_show_email/static/description/icon.png
  base_user_show_email/static/description/index.html
  base_user_show_email/views/login_layout.xml
  base_user_show_email/views/res_users_view.xml
Labels: approved, ready to merge
