Repository OCA/server-auth, pull requests merged in 2021-04, with the labels that each got.

#250 [13.0][MIG+IMP] users_ldap_groups: Migration to 13.0
  setup/users_ldap_groups/odoo/addons/users_ldap_groups
  setup/users_ldap_groups/setup.py
  users_ldap_groups/README.rst
  users_ldap_groups/__init__.py
  users_ldap_groups/__manifest__.py
  users_ldap_groups/i18n/de.po
  users_ldap_groups/i18n/es.po
  users_ldap_groups/i18n/fr.po
  users_ldap_groups/i18n/hr.po
  users_ldap_groups/i18n/pt_BR.po
  users_ldap_groups/i18n/sl.po
  users_ldap_groups/i18n/users_ldap_groups.pot
  users_ldap_groups/models/__init__.py
  users_ldap_groups/models/res_company_ldap.py
  users_ldap_groups/models/res_company_ldap_group_mapping.py
  users_ldap_groups/models/res_company_ldap_operator.py
  users_ldap_groups/models/res_users.py
  users_ldap_groups/readme/CONTRIBUTORS.rst
  users_ldap_groups/readme/DESCRIPTION.rst
  users_ldap_groups/readme/USAGE.rst
  users_ldap_groups/security/ir.model.access.csv
  users_ldap_groups/static/description/icon.png
  users_ldap_groups/static/description/index.html
  users_ldap_groups/tests/__init__.py
  users_ldap_groups/tests/test_users_ldap_groups.py
  users_ldap_groups/views/res_company_ldap_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#267 [13.0] update dotfiles
  .copier-answers.yml
  .flake8
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  auth_api_key/__manifest__.py
  auth_oauth_multi_token/__manifest__.py
  auth_session_timeout/__manifest__.py
  auth_session_timeout/tests/test_res_users.py
  auth_user_case_insensitive/tests/test_res_users.py
  password_security/__manifest__.py
  password_security/tests/test_password_security_home.py
  password_security/tests/test_res_users.py
  users_ldap_mail/__manifest__.py
  users_ldap_populate/__manifest__.py
  users_ldap_populate/tests/test_users_ldap_populate.py
Labels: bot is merging ⏳

#262 [13.0] auth_oauth_multi_token improvements
  auth_oauth_multi_token/models/auth_oauth_multi_token.py
  auth_oauth_multi_token/models/res_users.py
  auth_oauth_multi_token/readme/CONTRIBUTORS.rst
  auth_oauth_multi_token/tests/test_multi_token.py
  auth_oauth_multi_token/views/auth_oauth_multi_token.xml
  auth_oauth_multi_token/views/res_users.xml
Labels: approved, bot is merging ⏳, needs review

#258 [13.0][FIX] session timeout applies only to user
  auth_session_timeout/models/ir_http.py
Labels: approved, bot is merging ⏳
