Repository OCA/server-auth, pull requests merged in 2021-02, with the labels that each got.

#228 [12.0] FIX auth_saml committing saml_access_token otherwise login_and_redirect uses old data
  auth_saml/controllers/main.py
Labels: approved, bot is merging ⏳

#237 14.0 mig auth ldaps
  auth_ldaps/README.rst
  auth_ldaps/__init__.py
  auth_ldaps/__manifest__.py
  auth_ldaps/i18n/auth_ldaps.pot
  auth_ldaps/models/__init__.py
  auth_ldaps/models/res_company_ldap.py
  auth_ldaps/readme/CONFIGURE.rst
  auth_ldaps/readme/CONTRIBUTORS.rst
  auth_ldaps/readme/DESCRIPTION.rst
  auth_ldaps/readme/INSTALL.rst
  auth_ldaps/readme/USAGE.rst
  auth_ldaps/static/description/icon.png
  auth_ldaps/static/description/index.html
  auth_ldaps/views/res_company_ldap_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#199 [12.0][FIX] Add missing force_save attribute
  auth_totp/wizards/res_users_authenticator_create.xml
Labels: bot is merging ⏳

#242 [FIX] password_security: Increase timeout in tests
  password_security/tests/test_password_security_home.py
Labels: approved, bot is merging ⏳

#241 [13.0] [MIG] users_ldap_mail: Migration to 13.0
  setup/users_ldap_mail/odoo/addons/users_ldap_mail
  setup/users_ldap_mail/setup.py
  users_ldap_mail/README.rst
  users_ldap_mail/__init__.py
  users_ldap_mail/__manifest__.py
  users_ldap_mail/i18n/de.po
  users_ldap_mail/i18n/en.po
  users_ldap_mail/i18n/es.po
  users_ldap_mail/i18n/fr.po
  users_ldap_mail/i18n/hr.po
  users_ldap_mail/i18n/hr_HR.po
  users_ldap_mail/i18n/pt_BR.po
  users_ldap_mail/i18n/sl.po
  users_ldap_mail/i18n/users_ldap_mail.pot
  users_ldap_mail/i18n/zh_CN.po
  users_ldap_mail/models/__init__.py
  users_ldap_mail/models/users_ldap_model.py
  users_ldap_mail/readme/CONTRIBUTORS.rst
  users_ldap_mail/readme/DESCRIPTION.rst
  users_ldap_mail/readme/ROADMAP.rst
  users_ldap_mail/readme/USAGE.rst
  users_ldap_mail/static/description/icon.png
  users_ldap_mail/static/description/index.html
  users_ldap_mail/views/res_company_ldap.xml
Labels: approved, bot is merging ⏳
