Repository OCA/server-auth, pull requests merged in 2021-07, with the labels that each got.

#214 [13.0][MIG] auth_saml
  .travis.yml
  auth_saml/README.rst
  auth_saml/__init__.py
  auth_saml/__manifest__.py
  auth_saml/controllers/__init__.py
  auth_saml/controllers/main.py
  auth_saml/data/ir_config_parameter.xml
  auth_saml/i18n/auth_saml.pot
  auth_saml/i18n/fr.po
  auth_saml/models/__init__.py
  auth_saml/models/auth_saml_attribute_mapping.py
  auth_saml/models/auth_saml_provider.py
  auth_saml/models/auth_saml_request.py
  auth_saml/models/auth_saml_token.py
  auth_saml/models/res_config_settings.py
  auth_saml/models/res_users.py
  auth_saml/models/res_users_saml.py
  auth_saml/readme/CONFIGURE.rst
  auth_saml/readme/CONTRIBUTORS.rst
  auth_saml/readme/HISTORY.rst
  auth_saml/readme/INSTALL.rst
  auth_saml/security/ir.model.access.csv
  auth_saml/static/description/icon.png
  auth_saml/static/description/index.html
  auth_saml/tests/__init__.py
  auth_saml/tests/data/idp.pem
  auth_saml/tests/data/sp.key
  auth_saml/tests/data/sp.pem
  auth_saml/tests/fake_idp.py
  auth_saml/tests/test_pysaml.py
  auth_saml/views/auth_saml.xml
  auth_saml/views/res_config_settings.xml
  auth_saml/views/res_users.xml
  requirements.txt
  setup/auth_saml/odoo/addons/auth_saml
  setup/auth_saml/setup.py
Labels: bot is merging ⏳, migration

#263 [13.0][ADD] auth_jwt
  .eslintignore
  auth_jwt/README.rst
  auth_jwt/__init__.py
  auth_jwt/__manifest__.py
  auth_jwt/exceptions.py
  auth_jwt/models/__init__.py
  auth_jwt/models/auth_jwt_validator.py
  auth_jwt/models/ir_http.py
  auth_jwt/readme/CONTRIBUTORS.rst
  auth_jwt/readme/DESCRIPTION.rst
  auth_jwt/readme/INSTALL.rst
  auth_jwt/readme/ROADMAP.rst
  auth_jwt/readme/USAGE.rst
  auth_jwt/security/ir.model.access.csv
  auth_jwt/static/description/icon.png
  auth_jwt/tests/__init__.py
  auth_jwt/tests/test_auth_jwt.py
  auth_jwt/views/auth_jwt_validator_views.xml
  auth_jwt_demo/README.rst
  auth_jwt_demo/__init__.py
  auth_jwt_demo/__manifest__.py
  auth_jwt_demo/controllers/__init__.py
  auth_jwt_demo/controllers/main.py
  auth_jwt_demo/demo/auth_jwt_validator.xml
  auth_jwt_demo/readme/CONTRIBUTORS.rst
  auth_jwt_demo/readme/DESCRIPTION.rst
  auth_jwt_demo/readme/USAGE.rst
  auth_jwt_demo/static/description/icon.png
  auth_jwt_demo/tests/__init__.py
  auth_jwt_demo/tests/keycloak/keycloak-config.json
  auth_jwt_demo/tests/keycloak/keycloak.sh
  auth_jwt_demo/tests/spa/README.md
  auth_jwt_demo/tests/spa/auth_settings.json
  auth_jwt_demo/tests/spa/index.html
  auth_jwt_demo/tests/spa/js/app.js
  auth_jwt_demo/tests/spa/js/oidc-client.js
  auth_jwt_demo/tests/test_auth_jwt_demo.py
  setup/auth_jwt/odoo/addons/auth_jwt
  setup/auth_jwt/setup.py
  setup/auth_jwt_demo/odoo/addons/auth_jwt_demo
  setup/auth_jwt_demo/setup.py
  test-requirements.txt
Labels: approved, bot is merging ⏳, needs review

#275 [14.0][MIG] auth_jwt
  .eslintignore
  auth_jwt/README.rst
  auth_jwt/__init__.py
  auth_jwt/__manifest__.py
  auth_jwt/exceptions.py
  auth_jwt/models/__init__.py
  auth_jwt/models/auth_jwt_validator.py
  auth_jwt/models/ir_http.py
  auth_jwt/readme/CONTRIBUTORS.rst
  auth_jwt/readme/DESCRIPTION.rst
  auth_jwt/readme/INSTALL.rst
  auth_jwt/readme/USAGE.rst
  auth_jwt/security/ir.model.access.csv
  auth_jwt/static/description/icon.png
  auth_jwt/tests/__init__.py
  auth_jwt/tests/test_auth_jwt.py
  auth_jwt/views/auth_jwt_validator_views.xml
  auth_jwt_demo/README.rst
  auth_jwt_demo/__init__.py
  auth_jwt_demo/__manifest__.py
  auth_jwt_demo/controllers/__init__.py
  auth_jwt_demo/controllers/main.py
  auth_jwt_demo/demo/auth_jwt_validator.xml
  auth_jwt_demo/readme/CONTRIBUTORS.rst
  auth_jwt_demo/readme/DESCRIPTION.rst
  auth_jwt_demo/readme/USAGE.rst
  auth_jwt_demo/static/description/icon.png
  auth_jwt_demo/tests/__init__.py
  auth_jwt_demo/tests/keycloak/keycloak-config.json
  auth_jwt_demo/tests/keycloak/keycloak.sh
  auth_jwt_demo/tests/spa/README.md
  auth_jwt_demo/tests/spa/auth_settings.json
  auth_jwt_demo/tests/spa/index.html
  auth_jwt_demo/tests/spa/js/app.js
  auth_jwt_demo/tests/spa/js/oidc-client.js
  auth_jwt_demo/tests/test_auth_jwt_demo.py
  requirements.txt
  setup/auth_jwt/odoo/addons/auth_jwt
  setup/auth_jwt/setup.py
  setup/auth_jwt_demo/odoo/addons/auth_jwt_demo
  setup/auth_jwt_demo/setup.py
  test-requirements.txt
Labels: bot is merging ⏳, needs review
