Repository OCA/server-auth, pull requests merged in 2021-11, with the labels that each got.

#307 auth_api_key_group: fix form edit
  auth_api_key_group/views/auth_api_key_group_view.xml
Labels: needs review, bot is merging ⏳

#276 14.0 mig auth dynamic groups
  auth_dynamic_groups/README.rst
  auth_dynamic_groups/__init__.py
  auth_dynamic_groups/__manifest__.py
  auth_dynamic_groups/i18n/ar.po
  auth_dynamic_groups/i18n/auth_dynamic_groups.pot
  auth_dynamic_groups/i18n/ca.po
  auth_dynamic_groups/i18n/da.po
  auth_dynamic_groups/i18n/de.po
  auth_dynamic_groups/i18n/el_GR.po
  auth_dynamic_groups/i18n/en_US.po
  auth_dynamic_groups/i18n/es.po
  auth_dynamic_groups/i18n/es_ES.po
  auth_dynamic_groups/i18n/fi.po
  auth_dynamic_groups/i18n/fr.po
  auth_dynamic_groups/i18n/fr_CH.po
  auth_dynamic_groups/i18n/hr.po
  auth_dynamic_groups/i18n/hr_HR.po
  auth_dynamic_groups/i18n/it.po
  auth_dynamic_groups/i18n/nl.po
  auth_dynamic_groups/i18n/pt_BR.po
  auth_dynamic_groups/i18n/sl.po
  auth_dynamic_groups/i18n/tr.po
  auth_dynamic_groups/i18n/tr_TR.po
  auth_dynamic_groups/i18n/zh_CN.po
  auth_dynamic_groups/models/__init__.py
  auth_dynamic_groups/models/res_groups.py
  auth_dynamic_groups/models/res_users.py
  auth_dynamic_groups/readme/CONFIGURE.rst
  auth_dynamic_groups/readme/CONTRIBUTORS.rst
  auth_dynamic_groups/readme/CREDITS.rst
  auth_dynamic_groups/readme/DESCRIPTION.rst
  auth_dynamic_groups/readme/USAGE.rst
  auth_dynamic_groups/static/description/icon.png
  auth_dynamic_groups/static/description/index.html
  auth_dynamic_groups/tests/__init__.py
  auth_dynamic_groups/tests/test_auth_dynamic_groups.py
  auth_dynamic_groups/views/res_groups.xml
  setup/auth_dynamic_groups/odoo/addons/auth_dynamic_groups
  setup/auth_dynamic_groups/setup.py
Labels: approved, bot is merging ⏳

#308 [MIG][15.0] auth_api_key: Migration to 15.0
  auth_api_key/README.rst
  auth_api_key/__init__.py
  auth_api_key/__manifest__.py
  auth_api_key/i18n/auth_api_key.pot
  auth_api_key/i18n/it.po
  auth_api_key/models/__init__.py
  auth_api_key/models/auth_api_key.py
  auth_api_key/models/ir_http.py
  auth_api_key/readme/CONFIGURE.rst
  auth_api_key/readme/CONTRIBUTORS.rst
  auth_api_key/readme/DESCRIPTION.rst
  auth_api_key/readme/USAGE.rst
  auth_api_key/security/ir.model.access.csv
  auth_api_key/static/description/icon.png
  auth_api_key/static/description/index.html
  auth_api_key/tests/__init__.py
  auth_api_key/tests/test_auth_api_key.py
  auth_api_key/views/auth_api_key.xml
  setup/auth_api_key/odoo/addons/auth_api_key
  setup/auth_api_key/setup.py
Labels: approved, ready to merge

#311 [MIG][15.0] auth_api_key: Migration to 15.0
  auth_api_key/README.rst
  auth_api_key/__init__.py
  auth_api_key/__manifest__.py
  auth_api_key/i18n/auth_api_key.pot
  auth_api_key/i18n/it.po
  auth_api_key/models/__init__.py
  auth_api_key/models/auth_api_key.py
  auth_api_key/models/ir_http.py
  auth_api_key/readme/CONFIGURE.rst
  auth_api_key/readme/CONTRIBUTORS.rst
  auth_api_key/readme/DESCRIPTION.rst
  auth_api_key/readme/USAGE.rst
  auth_api_key/security/ir.model.access.csv
  auth_api_key/static/description/icon.png
  auth_api_key/static/description/index.html
  auth_api_key/tests/__init__.py
  auth_api_key/tests/test_auth_api_key.py
  auth_api_key/views/auth_api_key.xml
  setup/auth_api_key/odoo/addons/auth_api_key
  setup/auth_api_key/setup.py
Labels: bot is merging ⏳

#310 [15.0][MIG] auth_api_key_server_env: Migration to 15.0
  auth_api_key_server_env/README.rst
  auth_api_key_server_env/__init__.py
  auth_api_key_server_env/__manifest__.py
  auth_api_key_server_env/i18n/auth_api_key_server_env.pot
  auth_api_key_server_env/models/__init__.py
  auth_api_key_server_env/models/auth_api_key.py
  auth_api_key_server_env/readme/CONTRIBUTORS.rst
  auth_api_key_server_env/readme/DESCRIPTION.rst
  auth_api_key_server_env/static/description/icon.png
  auth_api_key_server_env/static/description/index.html
  auth_api_key_server_env/tests/__init__.py
  auth_api_key_server_env/tests/test_auth_api_key.py
  setup/auth_api_key_server_env/odoo/addons/auth_api_key_server_env
  setup/auth_api_key_server_env/setup.py
Labels: approved, bot is merging ⏳
