Repository OCA/server-auth, pull requests merged in 2022-11, with the labels that each got.

#430 [MIG] auth_signup_verify_email: Migration to 15.0
  auth_signup_verify_email/README.rst
  auth_signup_verify_email/__init__.py
  auth_signup_verify_email/__manifest__.py
  auth_signup_verify_email/controllers/__init__.py
  auth_signup_verify_email/controllers/main.py
  auth_signup_verify_email/i18n/ar.po
  auth_signup_verify_email/i18n/auth_signup_verify_email.pot
  auth_signup_verify_email/i18n/de.po
  auth_signup_verify_email/i18n/es.po
  auth_signup_verify_email/i18n/fr.po
  auth_signup_verify_email/i18n/hr.po
  auth_signup_verify_email/i18n/hr_HR.po
  auth_signup_verify_email/i18n/it.po
  auth_signup_verify_email/i18n/pt_BR.po
  auth_signup_verify_email/i18n/ro.po
  auth_signup_verify_email/i18n/sl.po
  auth_signup_verify_email/i18n/tr.po
  auth_signup_verify_email/readme/CONFIGURE.rst
  auth_signup_verify_email/readme/CONTRIBUTORS.rst
  auth_signup_verify_email/readme/DESCRIPTION.rst
  auth_signup_verify_email/readme/INSTALL.rst
  auth_signup_verify_email/readme/USAGE.rst
  auth_signup_verify_email/static/description/icon.png
  auth_signup_verify_email/static/description/icon.svg
  auth_signup_verify_email/static/description/index.html
  auth_signup_verify_email/tests/__init__.py
  auth_signup_verify_email/tests/test_verify_email.py
  auth_signup_verify_email/views/signup.xml
  requirements.txt
  setup/auth_signup_verify_email/odoo/addons/auth_signup_verify_email
  setup/auth_signup_verify_email/setup.py
Labels: approved, bot is merging ⏳

#350 [IMP][12.0] auth_oidc: allow assign groups from token claims
  auth_oidc/__manifest__.py
  auth_oidc/demo/local_keycloak.xml
  auth_oidc/models/auth_oauth_provider.py
  auth_oidc/models/res_users.py
  auth_oidc/security/ir.model.access.csv
  auth_oidc/static/description/index.html
  auth_oidc/tests/test_auth_oidc_auth_code.py
  auth_oidc/views/auth_oauth_provider.xml
Labels: approved, ready to merge, bot is merging ⏳, no stale

#421 [14.0][IMP][vault] Invalidate keys
  vault/controllers/main.py
  vault/models/res_users.py
  vault/static/src/js/vault_controller.js
  vault/tests/test_controller.py
  vault/tests/test_rights.py
  vault/tests/test_user.py
  vault/views/res_users_views.xml
Labels: bot is merging ⏳
