Repository OCA/server-auth, pull requests merged in 2022-06, with the labels that each got.

#388 [14.0][FIX] auth_signup_verify_email: Use real email address for tests
  auth_signup_verify_email/tests/test_verify_email.py
Labels: bot is merging ⏳

#374 [FIX][14.0][vault] Lock out of users when login changed
  vault/__manifest__.py
  vault/models/res_users.py
  vault/models/res_users_key.py
  vault/readme/DESCRIPTION.rst
  vault/static/src/js/vault.js
  vault/tests/test_vault.py
Labels: approved, bot is merging ⏳

#328 [14.0][FIX] auth_api_key_group: fix author name
  auth_api_key_group/README.rst
  auth_api_key_group/__manifest__.py
  auth_api_key_group/models/auth_api_key.py
  auth_api_key_group/models/auth_api_key_group.py
  auth_api_key_group/static/description/index.html
  auth_api_key_group/tests/test_auth_api_key_group.py
Labels: needs review, bot is merging ⏳

#343 [14.0] [IMP] auth_jwt: Add validator.next_validator_id to allow validator chaining
  auth_jwt/exceptions.py
  auth_jwt/models/auth_jwt_validator.py
  auth_jwt/models/ir_http.py
  auth_jwt/tests/test_auth_jwt.py
  auth_jwt/views/auth_jwt_validator_views.xml
Labels: approved, ready to merge, bot is merging ⏳
