Repository OCA/server-auth, pull requests merged in 2022-10, with the labels that each got.

#429 Place upper bound in cryptography indirect dependency
  auth_saml/__manifest__.py
  requirements.txt
Labels: needs review, bot is merging ⏳

#428 [15.0][MIG] auth_user_case_insensitive: Migration to 15.0 (rebased)
  auth_user_case_insensitive/README.rst
  auth_user_case_insensitive/__init__.py
  auth_user_case_insensitive/__manifest__.py
  auth_user_case_insensitive/hooks.py
  auth_user_case_insensitive/i18n/ar.po
  auth_user_case_insensitive/i18n/auth_user_case_insensitive.pot
  auth_user_case_insensitive/i18n/ca.po
  auth_user_case_insensitive/i18n/da.po
  auth_user_case_insensitive/i18n/de.po
  auth_user_case_insensitive/i18n/el_GR.po
  auth_user_case_insensitive/i18n/es.po
  auth_user_case_insensitive/i18n/es_ES.po
  auth_user_case_insensitive/i18n/fi.po
  auth_user_case_insensitive/i18n/fr.po
  auth_user_case_insensitive/i18n/fr_CH.po
  auth_user_case_insensitive/i18n/fr_FR.po
  auth_user_case_insensitive/i18n/hr.po
  auth_user_case_insensitive/i18n/hr_HR.po
  auth_user_case_insensitive/i18n/it.po
  auth_user_case_insensitive/i18n/lt.po
  auth_user_case_insensitive/i18n/nl.po
  auth_user_case_insensitive/i18n/nl_NL.po
  auth_user_case_insensitive/i18n/pt.po
  auth_user_case_insensitive/i18n/pt_BR.po
  auth_user_case_insensitive/i18n/ro.po
  auth_user_case_insensitive/i18n/sl.po
  auth_user_case_insensitive/i18n/tr.po
  auth_user_case_insensitive/i18n/tr_TR.po
  auth_user_case_insensitive/i18n/zh_CN.po
  auth_user_case_insensitive/models/__init__.py
  auth_user_case_insensitive/models/res_users.py
  auth_user_case_insensitive/readme/CONTRIBUTORS.rst
  auth_user_case_insensitive/readme/DESCRIPTION.rst
  auth_user_case_insensitive/readme/INSTALL.rst
  auth_user_case_insensitive/readme/USAGE.rst
  auth_user_case_insensitive/static/description/icon.png
  auth_user_case_insensitive/static/description/index.html
  auth_user_case_insensitive/tests/__init__.py
  auth_user_case_insensitive/tests/test_res_users.py
  setup/auth_user_case_insensitive/odoo/addons/auth_user_case_insensitive
  setup/auth_user_case_insensitive/setup.py
Labels: bot is merging ⏳

#425 [FIX] password_security: Non-admin users can keep the same password
  password_security/security/res_users_pass_history.xml
Labels: bug, needs review, bot is merging ⏳

#420 [13.0][IMP][vault] Invalidate keys
  vault/controllers/main.py
  vault/models/res_users.py
  vault/models/vault_right.py
  vault/static/src/js/vault_controller.js
  vault/tests/test_controller.py
  vault/tests/test_rights.py
  vault/tests/test_user.py
  vault/views/res_users_views.xml
Labels: bot is merging ⏳
