Repository OCA/server-auth, pull requests merged in 2022-01, with the labels that each got.

#324 [13.0][FIX] auth_saml: Get correct python package
  auth_saml/__manifest__.py
Labels: bot is merging ⏳

#329 Sync w/ OCA/oca-addons-repo-template
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .travis.yml
  README.md
Labels: needs review

#331 Fix missing travis lib
  .copier-answers.yml
  .travis.yml
  README.md
  auth_saml/__manifest__.py
Labels: needs review, bot is merging ⏳

#314 [14.0] [MIG] auth_oidc
  auth_oidc/README.rst
  auth_oidc/__init__.py
  auth_oidc/__manifest__.py
  auth_oidc/controllers/__init__.py
  auth_oidc/controllers/main.py
  auth_oidc/demo/local_keycloak.xml
  auth_oidc/i18n/auth_oidc.pot
  auth_oidc/models/__init__.py
  auth_oidc/models/auth_oauth_provider.py
  auth_oidc/models/res_users.py
  auth_oidc/readme/CONFIGURE.rst
  auth_oidc/readme/CONTRIBUTORS.rst
  auth_oidc/readme/DESCRIPTION.rst
  auth_oidc/readme/HISTORY.rst
  auth_oidc/readme/INSTALL.rst
  auth_oidc/readme/ROADMAP.rst
  auth_oidc/readme/USAGE.rst
  auth_oidc/static/description/icon.png
  auth_oidc/static/description/index.html
  auth_oidc/tests/__init__.py
  auth_oidc/tests/keycloak/keycloak-config.json
  auth_oidc/tests/keycloak/keycloak.sh
  auth_oidc/tests/test_auth_oidc_auth_code.py
  auth_oidc/views/auth_oauth_provider.xml
  requirements.txt
  setup/auth_oidc/odoo/addons/auth_oidc
  setup/auth_oidc/setup.py
Labels: approved, bot is merging ⏳

#332 [14.0][UPD] auth_api_key(_server_env) development status
  auth_api_key/__manifest__.py
  auth_api_key_server_env/__manifest__.py
Labels: approved, bot is merging ⏳

#320 [15.0][MIG] auth_jwt,auth_jwt_demo: pre-migrate to V15
  .pre-commit-config.yaml
  auth_jwt/README.rst
  auth_jwt/__init__.py
  auth_jwt/__manifest__.py
  auth_jwt/exceptions.py
  auth_jwt/i18n/auth_jwt.pot
  auth_jwt/models/__init__.py
  auth_jwt/models/auth_jwt_validator.py
  auth_jwt/models/ir_http.py
  auth_jwt/readme/CONTRIBUTORS.rst
  auth_jwt/readme/DESCRIPTION.rst
  auth_jwt/readme/INSTALL.rst
  auth_jwt/readme/USAGE.rst
  auth_jwt/security/ir.model.access.csv
  auth_jwt/static/description/icon.png
  auth_jwt/static/description/index.html
  auth_jwt/tests/__init__.py
  auth_jwt/tests/test_auth_jwt.py
  auth_jwt/views/auth_jwt_validator_views.xml
  auth_jwt_demo/README.rst
  auth_jwt_demo/__init__.py
  auth_jwt_demo/__manifest__.py
  auth_jwt_demo/controllers/__init__.py
  auth_jwt_demo/controllers/main.py
  auth_jwt_demo/demo/auth_jwt_validator.xml
  auth_jwt_demo/i18n/auth_jwt_demo.pot
  auth_jwt_demo/readme/CONTRIBUTORS.rst
  auth_jwt_demo/readme/DESCRIPTION.rst
  auth_jwt_demo/readme/USAGE.rst
  auth_jwt_demo/static/description/icon.png
  auth_jwt_demo/static/description/index.html
  auth_jwt_demo/tests/__init__.py
  auth_jwt_demo/tests/keycloak/keycloak-config.json
  auth_jwt_demo/tests/keycloak/keycloak.sh
  auth_jwt_demo/tests/spa/README.md
  auth_jwt_demo/tests/spa/auth_settings.json
  auth_jwt_demo/tests/spa/index.html
  auth_jwt_demo/tests/spa/js/app.js
  auth_jwt_demo/tests/spa/js/oidc-client.js
  auth_jwt_demo/tests/test_auth_jwt_demo.py
Labels: bot is merging ⏳

#270 [14.0][MIG] auth_signup_verify_email
  auth_signup_verify_email/README.rst
  auth_signup_verify_email/__init__.py
  auth_signup_verify_email/__manifest__.py
  auth_signup_verify_email/controllers/__init__.py
  auth_signup_verify_email/controllers/main.py
  auth_signup_verify_email/i18n/ar.po
  auth_signup_verify_email/i18n/auth_signup_verify_email.pot
  auth_signup_verify_email/i18n/de.po
  auth_signup_verify_email/i18n/es.po
  auth_signup_verify_email/i18n/fr.po
  auth_signup_verify_email/i18n/hr.po
  auth_signup_verify_email/i18n/hr_HR.po
  auth_signup_verify_email/i18n/it.po
  auth_signup_verify_email/i18n/pt_BR.po
  auth_signup_verify_email/i18n/ro.po
  auth_signup_verify_email/i18n/sl.po
  auth_signup_verify_email/i18n/tr.po
  auth_signup_verify_email/readme/CONFIGURE.rst
  auth_signup_verify_email/readme/CONTRIBUTORS.rst
  auth_signup_verify_email/readme/DESCRIPTION.rst
  auth_signup_verify_email/readme/INSTALL.rst
  auth_signup_verify_email/readme/USAGE.rst
  auth_signup_verify_email/static/description/icon.png
  auth_signup_verify_email/static/description/icon.svg
  auth_signup_verify_email/static/description/index.html
  auth_signup_verify_email/tests/__init__.py
  auth_signup_verify_email/tests/test_verify_email.py
  auth_signup_verify_email/views/signup.xml
  requirements.txt
  setup/auth_signup_verify_email/odoo/addons/auth_signup_verify_email
  setup/auth_signup_verify_email/setup.py
Labels: approved, bot is merging ⏳

#334 auth_api_key_group: dev status -> Beta
  auth_api_key_group/__manifest__.py
Labels: needs review, bot is merging ⏳
