Repository OCA/server-auth, pull requests merged in 2022-07, with the labels that each got.

#385 [IMP] Update templates with copier
  .copier-answers.yml
  .github/workflows/test.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
  auth_oauth_autologin/tests/test_auth_oauth_autologin.py
  auth_signup_verify_email/tests/test_verify_email.py
Labels: bot is merging ⏳

#394 [14.0][FIX] auth_admin_passkey: error in README
  auth_admin_passkey/readme/CONFIGURE.rst
Labels: approved, bot is merging ⏳

#396 [14.0][FIX] auth_api_key: fix archived user allowed key
  auth_api_key/models/auth_api_key.py
  auth_api_key/tests/test_auth_api_key.py
Labels: bug, approved, bot is merging ⏳

#398 [15.0] forward port auth_api_key: fix archived user allowed key
  auth_api_key/models/auth_api_key.py
  auth_api_key/tests/test_auth_api_key.py
Labels: bug, bot is merging ⏳

#397 [13.0] backport auth_api_key: fix archived user allowed key
  auth_api_key/models/auth_api_key.py
  auth_api_key/tests/test_auth_api_key.py
Labels: bug, bot is merging ⏳

#400 [14.0] Revert auth_api_key: fix api key archived user
  auth_api_key/i18n/auth_api_key.pot
  auth_api_key/i18n/it.po
  auth_api_key/models/auth_api_key.py
  auth_api_key/tests/test_auth_api_key.py
Labels: bug, approved, bot is merging ⏳

#401 [15.0] Revert auth_api_key: fix api key archived user
  auth_api_key/i18n/auth_api_key.pot
  auth_api_key/i18n/it.po
  auth_api_key/models/auth_api_key.py
  auth_api_key/tests/test_auth_api_key.py
Labels: bug, bot is merging ⏳

#402 [13.0] Revert auth_api_key: fix api key archived user
  auth_api_key/i18n/auth_api_key.pot
  auth_api_key/models/auth_api_key.py
  auth_api_key/tests/test_auth_api_key.py
Labels: bug, bot is merging ⏳
