Repository OCA/server-auth, pull requests merged in 2022-03, with the labels that each got.

#338 [IMP] timeout check triggered on session uid
  auth_session_timeout/models/ir_http.py
Labels: approved, bot is merging ⏳

#347 [15.0][MIG] auth_session_timeout
  auth_session_timeout/README.rst
  auth_session_timeout/__init__.py
  auth_session_timeout/__manifest__.py
  auth_session_timeout/data/ir_config_parameter_data.xml
  auth_session_timeout/i18n/ar.po
  auth_session_timeout/i18n/auth_session_timeout.pot
  auth_session_timeout/i18n/ca.po
  auth_session_timeout/i18n/da.po
  auth_session_timeout/i18n/de.po
  auth_session_timeout/i18n/el_GR.po
  auth_session_timeout/i18n/es.po
  auth_session_timeout/i18n/es_ES.po
  auth_session_timeout/i18n/fi.po
  auth_session_timeout/i18n/fr.po
  auth_session_timeout/i18n/fr_CH.po
  auth_session_timeout/i18n/fr_FR.po
  auth_session_timeout/i18n/hr.po
  auth_session_timeout/i18n/hr_HR.po
  auth_session_timeout/i18n/it.po
  auth_session_timeout/i18n/nl.po
  auth_session_timeout/i18n/nl_NL.po
  auth_session_timeout/i18n/pt.po
  auth_session_timeout/i18n/pt_BR.po
  auth_session_timeout/i18n/ro.po
  auth_session_timeout/i18n/sl.po
  auth_session_timeout/i18n/tr.po
  auth_session_timeout/i18n/tr_TR.po
  auth_session_timeout/i18n/zh_CN.po
  auth_session_timeout/models/__init__.py
  auth_session_timeout/models/ir_config_parameter.py
  auth_session_timeout/models/ir_http.py
  auth_session_timeout/models/res_users.py
  auth_session_timeout/readme/CONFIGURE.rst
  auth_session_timeout/readme/CONTRIBUTORS.rst
  auth_session_timeout/readme/DESCRIPTION.rst
  auth_session_timeout/readme/USAGE.rst
  auth_session_timeout/static/description/icon.png
  auth_session_timeout/static/description/index.html
  auth_session_timeout/tests/__init__.py
  auth_session_timeout/tests/test_ir_config_parameter.py
  auth_session_timeout/tests/test_res_users.py
  setup/auth_session_timeout/odoo/addons/auth_session_timeout
  setup/auth_session_timeout/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#354 [14.0] [FIX] auth_oidc: Fix werkzeug deprecated warning for url_encode, url_decode
  auth_oidc/controllers/main.py
Labels: approved, ready to merge, bot is merging ⏳

#115 [12.0][mig] auth_totp_password_security
  auth_totp_password_security/README.rst
  auth_totp_password_security/__init__.py
  auth_totp_password_security/__manifest__.py
  auth_totp_password_security/controllers/__init__.py
  auth_totp_password_security/controllers/main.py
  auth_totp_password_security/i18n/auth_totp_password_security.pot
  auth_totp_password_security/static/description/icon.png
  auth_totp_password_security/tests/__init__.py
  auth_totp_password_security/tests/test_main.py
Labels: approved, ready to merge, bot is merging ⏳

#303 [12.0][FIX] fix ldaps certificate verification
  auth_ldaps/models/res_company_ldap.py
Labels: approved, bot is merging ⏳

#359 [14.0][FIX] fix ldaps certificate verification
  auth_ldaps/models/res_company_ldap.py
Labels: bot is merging ⏳

#358 [13.0][FIX] fix ldaps certificate verification
  auth_ldaps/models/res_company_ldap.py
Labels: bot is merging ⏳

#342 [15.0][FIX][IMP] Fix and improve auth_saml
  auth_saml/README.rst
  auth_saml/__init__.py
  auth_saml/__manifest__.py
  auth_saml/controllers/main.py
  auth_saml/data/ir_config_parameter.xml
  auth_saml/i18n/auth_saml.pot
  auth_saml/models/__init__.py
  auth_saml/models/auth_saml_attribute_mapping.py
  auth_saml/models/auth_saml_provider.py
  auth_saml/models/auth_saml_request.py
  auth_saml/models/auth_saml_token.py
  auth_saml/models/ir_config_parameter.py
  auth_saml/models/res_config_settings.py
  auth_saml/models/res_users.py
  auth_saml/models/res_users_saml.py
  auth_saml/readme/CONFIGURE.rst
  auth_saml/readme/CONTRIBUTORS.rst
  auth_saml/readme/DESCRIPTION.rst
  auth_saml/readme/HISTORY.rst
  auth_saml/readme/INSTALL.rst
  auth_saml/readme/ROADMAP.rst
  auth_saml/readme/USAGE.rst
  auth_saml/security/ir.model.access.csv
  auth_saml/static/description/index.html
  auth_saml/tests/__init__.py
  auth_saml/tests/fake_idp.py
  auth_saml/tests/test_pysaml.py
  auth_saml/views/auth_saml.xml
  setup/auth_saml/setup.py
Labels: bot is merging ⏳
