Repository OCA/server-auth, pull requests merged in 2023-12, with the labels that each got.

#583 [15.0] auth_oidc: OpenID Connect fixes from 14.0
  auth_oidc/__manifest__.py
  auth_oidc/models/auth_oauth_provider.py
  auth_oidc/models/res_users.py
  auth_oidc/readme/CONTRIBUTORS.rst
  auth_oidc/readme/HISTORY.rst
  auth_oidc/tests/test_auth_oidc_auth_code.py
  test-requirements.txt
Labels: bot is merging ⏳

#587 Small bugfix, RelayState can be empty
  auth_saml/controllers/main.py
Labels: bot is merging ⏳

#588 [15.0][FIX] auth_saml: RelayState can be empty
  auth_saml/controllers/main.py
Labels: bot is merging ⏳

#589 [14.0][FIX] auth_saml: RelayState can be empty
  auth_saml/controllers/main.py
Labels: bot is merging ⏳

#590 [13.0][FIX] auth_saml: RelayState can be empty
  auth_saml/controllers/main.py
Labels: bot is merging ⏳

#493 Add auth_oauth_ropc
  auth_oauth_ropc/README.rst
  auth_oauth_ropc/__init__.py
  auth_oauth_ropc/__manifest__.py
  auth_oauth_ropc/models/__init__.py
  auth_oauth_ropc/models/oauth_ropc_provider.py
  auth_oauth_ropc/models/res_users.py
  auth_oauth_ropc/readme/CONFIGURE.rst
  auth_oauth_ropc/readme/CONTRIBUTORS.rst
  auth_oauth_ropc/readme/DESCRIPTION.rst
  auth_oauth_ropc/readme/USAGE.rst
  auth_oauth_ropc/security/oauth_ropc_provider.xml
  auth_oauth_ropc/static/description/configuration.png
  auth_oauth_ropc/static/description/icon.png
  auth_oauth_ropc/static/description/index.html
  auth_oauth_ropc/views/oauth_ropc_provider.xml
  setup/auth_oauth_ropc/odoo/addons/auth_oauth_ropc
  setup/auth_oauth_ropc/setup.py
Labels: bot is merging ⏳, stale

#597 [15.0][MIG]user_log_view: Migration to 15.0
  setup/user_log_view/odoo/addons/user_log_view
  setup/user_log_view/setup.py
  user_log_view/README.rst
  user_log_view/__init__.py
  user_log_view/__manifest__.py
  user_log_view/i18n/user_log_view.pot
  user_log_view/readme/CONTRIBUTORS.rst
  user_log_view/readme/DESCRIPTION.rst
  user_log_view/readme/USAGE.rst
  user_log_view/static/description/icon.png
  user_log_view/static/description/index.html
  user_log_view/views/res_users_views.xml
Labels: approved, bot is merging ⏳
