Repository OCA/server-auth, pull requests merged in 2023-10, with the labels that each got.

#561 [16.0] Add auth_oidc_environment
  auth_oidc_environment/README.rst
  auth_oidc_environment/__init__.py
  auth_oidc_environment/__manifest__.py
  auth_oidc_environment/models/__init__.py
  auth_oidc_environment/models/auth_oauth_provider.py
  auth_oidc_environment/readme/CONFIGURE.rst
  auth_oidc_environment/readme/CONTRIBUTORS.rst
  auth_oidc_environment/readme/DESCRIPTION.rst
  auth_oidc_environment/readme/USAGE.rst
  auth_oidc_environment/static/description/icon.png
  auth_oidc_environment/static/description/index.html
  auth_oidc_environment/tests/__init__.py
  auth_oidc_environment/tests/test_auth_oidc_environment.py
  setup/auth_oidc_environment/odoo/addons/auth_oidc_environment
  setup/auth_oidc_environment/setup.py
Labels: approved, bot is merging ⏳

#560 [15.0][IMP] vault: Add new groups to allow importing/exporting secrets
  vault/__manifest__.py
  vault/models/res_config_settings.py
  vault/security/vault_security.xml
  vault/views/res_config_settings_views.xml
  vault/views/vault_entry_views.xml
  vault/views/vault_views.xml
Labels: approved, bot is merging ⏳

#548 [16.0][IMP] auth_oidc: Add AzureAD code flow provider
  auth_oidc/__manifest__.py
  auth_oidc/data/auth_oauth_data.xml
  auth_oidc/readme/CONFIGURE.rst
  auth_oidc/static/description/oauth-microsoft_azure-api_permissions.png
  auth_oidc/static/description/oauth-microsoft_azure-optional_claims.png
  auth_oidc/static/description/odoo-azure_ad_multitenant.png
Labels: bot is merging ⏳

#566 [15.0][IMP] server-auth: test performance improvement
  auth_oauth_multi_token/tests/test_multi_token.py
Labels: bot is merging ⏳

#567 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  auth_jwt/i18n/auth_jwt.pot
  auth_jwt/views/auth_jwt_validator_views.xml
  auth_user_case_insensitive/tests/test_res_users.py
Labels: help wanted, needs review, bot is merging ⏳
