Repository OCA/server-auth, pull requests merged in 2023-01, with the labels that each got.

#454 [15.0][MIG] users_ldap_groups
  requirements.txt
  setup/users_ldap_groups/odoo/addons/users_ldap_groups
  setup/users_ldap_groups/setup.py
  users_ldap_groups/README.rst
  users_ldap_groups/__init__.py
  users_ldap_groups/__manifest__.py
  users_ldap_groups/i18n/de.po
  users_ldap_groups/i18n/es.po
  users_ldap_groups/i18n/fr.po
  users_ldap_groups/i18n/hr.po
  users_ldap_groups/i18n/it.po
  users_ldap_groups/i18n/pt_BR.po
  users_ldap_groups/i18n/sl.po
  users_ldap_groups/i18n/users_ldap_groups.pot
  users_ldap_groups/models/__init__.py
  users_ldap_groups/models/res_company_ldap.py
  users_ldap_groups/models/res_company_ldap_group_mapping.py
  users_ldap_groups/models/res_company_ldap_operator.py
  users_ldap_groups/models/res_users.py
  users_ldap_groups/readme/CONTRIBUTORS.rst
  users_ldap_groups/readme/DESCRIPTION.rst
  users_ldap_groups/readme/USAGE.rst
  users_ldap_groups/security/ir.model.access.csv
  users_ldap_groups/static/description/icon.png
  users_ldap_groups/static/description/index.html
  users_ldap_groups/tests/__init__.py
  users_ldap_groups/tests/test_users_ldap_groups.py
  users_ldap_groups/views/res_company_ldap_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#393 [15.0][MIG] auth_oidc: Migration to 15.0
  auth_oidc/README.rst
  auth_oidc/__init__.py
  auth_oidc/__manifest__.py
  auth_oidc/controllers/__init__.py
  auth_oidc/controllers/main.py
  auth_oidc/demo/local_keycloak.xml
  auth_oidc/i18n/auth_oidc.pot
  auth_oidc/models/__init__.py
  auth_oidc/models/auth_oauth_provider.py
  auth_oidc/models/res_users.py
  auth_oidc/readme/CONFIGURE.rst
  auth_oidc/readme/CONTRIBUTORS.rst
  auth_oidc/readme/DESCRIPTION.rst
  auth_oidc/readme/HISTORY.rst
  auth_oidc/readme/INSTALL.rst
  auth_oidc/readme/ROADMAP.rst
  auth_oidc/readme/USAGE.rst
  auth_oidc/static/description/icon.png
  auth_oidc/static/description/index.html
  auth_oidc/tests/__init__.py
  auth_oidc/tests/keycloak/keycloak-config.json
  auth_oidc/tests/keycloak/keycloak.sh
  auth_oidc/tests/test_auth_oidc_auth_code.py
  auth_oidc/views/auth_oauth_provider.xml
  requirements.txt
  setup/auth_oidc/odoo/addons/auth_oidc
  setup/auth_oidc/setup.py
Labels: approved, bot is merging ⏳, stale

#459 [13.0][FIX] vault_share: File is not downloaded when clicking sharing link
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  requirements.txt
  users_ldap_mail/i18n/en.po
  vault_share/static/src/js/vault_share.js
Labels: approved, bot is merging ⏳

#460 [14.0][FIX] vault_share: File is not downloaded when clicking sharing link
  vault_share/static/src/js/vault_share.js
Labels: approved, bot is merging ⏳

#463 [FIX][14.0]users_ldap_mail force the cast in string in case of the Active directory is prov…
  users_ldap_mail/models/users_ldap_model.py
Labels: approved, bot is merging ⏳
