Repository OCA/server-auth, pull requests merged in 2023-08, with the labels that each got.

#545 [15.0][IMP] vault: Add reload when finish the reencriptation to display updated data
  vault/static/src/legacy/vault_controller.js
Labels: approved, bot is merging ⏳

#542 [BACKPORT][FIX][13.0] vault: Rework of re-encryption process
  vault/controllers/main.py
  vault/models/abstract_vault_field.py
  vault/models/vault.py
  vault/models/vault_entry.py
  vault/models/vault_right.py
  vault/static/src/js/vault_controller.js
  vault/tests/test_controller.py
  vault/tests/test_rights.py
  vault/views/vault_views.xml
Labels: bot is merging ⏳

#541 [BACKPORT][FIX][14.0] vault: Rework of re-encryption process
  vault/controllers/main.py
  vault/models/abstract_vault_field.py
  vault/models/vault.py
  vault/models/vault_entry.py
  vault/models/vault_right.py
  vault/static/src/js/vault_controller.js
  vault/tests/test_controller.py
  vault/tests/test_rights.py
  vault/views/vault_views.xml
Labels: bot is merging ⏳

#485 auth_saml: add maintainer
  auth_saml/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#536 auth_saml: add maintainer
  auth_saml/__manifest__.py
Labels: approved, bot is merging ⏳

#512 [16.0][MIG] users_ldap_mail: Migration to version 16.0
  setup/users_ldap_mail/odoo/addons/users_ldap_mail
  setup/users_ldap_mail/setup.py
  users_ldap_mail/README.rst
  users_ldap_mail/__init__.py
  users_ldap_mail/__manifest__.py
  users_ldap_mail/i18n/de.po
  users_ldap_mail/i18n/es.po
  users_ldap_mail/i18n/fr.po
  users_ldap_mail/i18n/hr.po
  users_ldap_mail/i18n/hr_HR.po
  users_ldap_mail/i18n/pt_BR.po
  users_ldap_mail/i18n/sl.po
  users_ldap_mail/i18n/users_ldap_mail.pot
  users_ldap_mail/i18n/zh_CN.po
  users_ldap_mail/models/__init__.py
  users_ldap_mail/models/users_ldap_model.py
  users_ldap_mail/readme/CONTRIBUTORS.rst
  users_ldap_mail/readme/DESCRIPTION.rst
  users_ldap_mail/readme/ROADMAP.rst
  users_ldap_mail/readme/USAGE.rst
  users_ldap_mail/static/description/icon.png
  users_ldap_mail/static/description/index.html
  users_ldap_mail/views/res_company_ldap.xml
Labels: bot is merging ⏳

#529 [16.0] [MIG] user_log_view
  setup/user_log_view/odoo/addons/user_log_view
  setup/user_log_view/setup.py
  user_log_view/README.rst
  user_log_view/__init__.py
  user_log_view/__manifest__.py
  user_log_view/i18n/user_log_view.pot
  user_log_view/readme/CONTRIBUTORS.rst
  user_log_view/readme/DESCRIPTION.rst
  user_log_view/readme/USAGE.rst
  user_log_view/static/description/icon.png
  user_log_view/static/description/index.html
  user_log_view/views/res_users_views.xml
Labels: bot is merging ⏳
