Repository OCA/server-auth, pull requests merged in 2023-03, with the labels that each got.

#490 [15.0][IMP] password_security: Calculate score correctly w/o char type reqs.
  password_security/__manifest__.py
  password_security/static/src/js/password_gauge.js
  password_security/static/tests/auth_password_policy_tests.js
Labels: approved, ready to merge, bot is merging ⏳

#495 [15.0][IMP] password_security: Speed up tests.
  password_security/tests/test_res_users.py
Labels: approved, bot is merging ⏳

#468 [15.0][ADD] auth_signup_partner_company
  auth_signup_partner_company/README.rst
  auth_signup_partner_company/__init__.py
  auth_signup_partner_company/__manifest__.py
  auth_signup_partner_company/models/__init__.py
  auth_signup_partner_company/models/res_users.py
  auth_signup_partner_company/readme/DESCRIPTION.rst
  auth_signup_partner_company/static/description/index.html
  auth_signup_partner_company/tests/__init__.py
  auth_signup_partner_company/tests/test_auth_signup_partner_company.py
  setup/auth_signup_partner_company/odoo/addons/auth_signup_partner_company
  setup/auth_signup_partner_company/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#462 [16.0][MIG] auth_admin_passkey: migration to 16.0
  auth_admin_passkey/README.rst
  auth_admin_passkey/__init__.py
  auth_admin_passkey/__manifest__.py
  auth_admin_passkey/i18n/ar.po
  auth_admin_passkey/i18n/auth_admin_passkey.pot
  auth_admin_passkey/i18n/ca.po
  auth_admin_passkey/i18n/da.po
  auth_admin_passkey/i18n/de.po
  auth_admin_passkey/i18n/el_GR.po
  auth_admin_passkey/i18n/es.po
  auth_admin_passkey/i18n/es_ES.po
  auth_admin_passkey/i18n/fi.po
  auth_admin_passkey/i18n/fr.po
  auth_admin_passkey/i18n/fr_CH.po
  auth_admin_passkey/i18n/fr_FR.po
  auth_admin_passkey/i18n/hr.po
  auth_admin_passkey/i18n/hr_HR.po
  auth_admin_passkey/i18n/it.po
  auth_admin_passkey/i18n/nl.po
  auth_admin_passkey/i18n/nl_NL.po
  auth_admin_passkey/i18n/pt.po
  auth_admin_passkey/i18n/pt_BR.po
  auth_admin_passkey/i18n/ro.po
  auth_admin_passkey/i18n/sl.po
  auth_admin_passkey/i18n/tr.po
  auth_admin_passkey/i18n/tr_TR.po
  auth_admin_passkey/i18n/zh_CN.po
  auth_admin_passkey/models/__init__.py
  auth_admin_passkey/models/res_users.py
  auth_admin_passkey/readme/CONFIGURE.rst
  auth_admin_passkey/readme/CONTRIBUTORS.rst
  auth_admin_passkey/readme/DESCRIPTION.rst
  auth_admin_passkey/static/description/icon.png
  auth_admin_passkey/static/description/index.html
  auth_admin_passkey/tests/__init__.py
  auth_admin_passkey/tests/test_auth_admin_passkey.py
  auth_admin_passkey/tests/test_ui.py
  setup/auth_admin_passkey/odoo/addons/auth_admin_passkey
  setup/auth_admin_passkey/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#498 [16.0][MIG] auth_saml: Migration to 16.0
  auth_saml/README.rst
  auth_saml/__init__.py
  auth_saml/__manifest__.py
  auth_saml/controllers/__init__.py
  auth_saml/controllers/main.py
  auth_saml/data/ir_config_parameter.xml
  auth_saml/i18n/auth_saml.pot
  auth_saml/i18n/fr.po
  auth_saml/models/__init__.py
  auth_saml/models/auth_saml_attribute_mapping.py
  auth_saml/models/auth_saml_provider.py
  auth_saml/models/auth_saml_request.py
  auth_saml/models/ir_config_parameter.py
  auth_saml/models/res_config_settings.py
  auth_saml/models/res_users.py
  auth_saml/models/res_users_saml.py
  auth_saml/readme/CONFIGURE.rst
  auth_saml/readme/CONTRIBUTORS.rst
  auth_saml/readme/DESCRIPTION.rst
  auth_saml/readme/HISTORY.rst
  auth_saml/readme/INSTALL.rst
  auth_saml/readme/ROADMAP.rst
  auth_saml/readme/USAGE.rst
  auth_saml/security/ir.model.access.csv
  auth_saml/static/description/icon.png
  auth_saml/static/description/index.html
  auth_saml/tests/__init__.py
  auth_saml/tests/data/idp.pem
  auth_saml/tests/data/sp.key
  auth_saml/tests/data/sp.pem
  auth_saml/tests/fake_idp.py
  auth_saml/tests/test_pysaml.py
  auth_saml/views/auth_saml.xml
  auth_saml/views/res_config_settings.xml
  auth_saml/views/res_users.xml
  requirements.txt
  setup/auth_saml/odoo/addons/auth_saml
  setup/auth_saml/setup.py
Labels: bot is merging ⏳
