Repository OCA/server-auth, pull requests merged in 2023-06, with the labels that each got.

#519 [16.0] mig auth_jwt and auth_jwt_demo
  .eslintignore
  auth_jwt/README.rst
  auth_jwt/__init__.py
  auth_jwt/__manifest__.py
  auth_jwt/exceptions.py
  auth_jwt/i18n/auth_jwt.pot
  auth_jwt/models/__init__.py
  auth_jwt/models/auth_jwt_validator.py
  auth_jwt/models/ir_http.py
  auth_jwt/readme/CONTRIBUTORS.rst
  auth_jwt/readme/DESCRIPTION.rst
  auth_jwt/readme/INSTALL.rst
  auth_jwt/readme/USAGE.rst
  auth_jwt/security/ir.model.access.csv
  auth_jwt/static/description/icon.png
  auth_jwt/static/description/index.html
  auth_jwt/tests/__init__.py
  auth_jwt/tests/test_auth_jwt.py
  auth_jwt/views/auth_jwt_validator_views.xml
  auth_jwt_demo/README.rst
  auth_jwt_demo/__init__.py
  auth_jwt_demo/__manifest__.py
  auth_jwt_demo/controllers/__init__.py
  auth_jwt_demo/controllers/main.py
  auth_jwt_demo/demo/auth_jwt_validator.xml
  auth_jwt_demo/i18n/auth_jwt_demo.pot
  auth_jwt_demo/readme/CONTRIBUTORS.rst
  auth_jwt_demo/readme/DESCRIPTION.rst
  auth_jwt_demo/readme/USAGE.rst
  auth_jwt_demo/static/description/icon.png
  auth_jwt_demo/static/description/index.html
  auth_jwt_demo/tests/__init__.py
  auth_jwt_demo/tests/keycloak/keycloak-config.json
  auth_jwt_demo/tests/keycloak/keycloak.sh
  auth_jwt_demo/tests/spa/README.md
  auth_jwt_demo/tests/spa/auth_settings.json
  auth_jwt_demo/tests/spa/index.html
  auth_jwt_demo/tests/spa/js/app.js
  auth_jwt_demo/tests/spa/js/oidc-client.js
  auth_jwt_demo/tests/test_auth_jwt_demo.py
  requirements.txt
  setup/auth_jwt/odoo/addons/auth_jwt
  setup/auth_jwt/setup.py
  setup/auth_jwt_demo/odoo/addons/auth_jwt_demo
  setup/auth_jwt_demo/setup.py
Labels: approved, bot is merging ⏳

#520 [16.0] auth_jwt: add cookie mode
  auth_jwt/exceptions.py
  auth_jwt/models/auth_jwt_validator.py
  auth_jwt/models/ir_http.py
  auth_jwt/readme/USAGE.rst
  auth_jwt/tests/test_auth_jwt.py
  auth_jwt/views/auth_jwt_validator_views.xml
  auth_jwt_demo/controllers/main.py
  auth_jwt_demo/demo/auth_jwt_validator.xml
  auth_jwt_demo/tests/test_auth_jwt_demo.py
Labels: approved, ready to merge, bot is merging ⏳

#530 [15.0][FIX] vault, vault_share: Error on test
  vault/tests/test_controller.py
  vault_share/tests/test_share.py
Labels: approved, bot is merging ⏳

#474 [13.0][IMP] timeout check triggered on session uid
  auth_session_timeout/models/ir_http.py
Labels: bot is merging ⏳, no stale
