Repository OCA/server-auth, pull requests merged in 2023-07, with the labels that each got.

#491 [15.0][FIX] password_security: constraint of password_estimate range
  password_security/models/res_company.py
  password_security/readme/CONTRIBUTORS.rst
  password_security/tests/__init__.py
  password_security/tests/test_res_config_settings.py
Labels: approved, bot is merging ⏳, stale

#494 [15.0][FIX] password_security: correctly look at previous password history
  password_security/models/res_users.py
  password_security/tests/__init__.py
  password_security/tests/test_password_history.py
Labels: approved, bot is merging ⏳

#509 [FIX]auth_saml: fix singleton error.
  auth_saml/models/res_users.py
Labels: approved, ready to merge, bot is merging ⏳

#510 [15.0][FIX] auth_saml: fix singleton error.
  auth_saml/models/res_users.py
Labels: approved, ready to merge, bot is merging ⏳

#362 [15.0][MIG] auth_admin_passkey
  auth_admin_passkey/README.rst
  auth_admin_passkey/__init__.py
  auth_admin_passkey/__manifest__.py
  auth_admin_passkey/i18n/ar.po
  auth_admin_passkey/i18n/auth_admin_passkey.pot
  auth_admin_passkey/i18n/ca.po
  auth_admin_passkey/i18n/da.po
  auth_admin_passkey/i18n/de.po
  auth_admin_passkey/i18n/el_GR.po
  auth_admin_passkey/i18n/es.po
  auth_admin_passkey/i18n/es_ES.po
  auth_admin_passkey/i18n/fi.po
  auth_admin_passkey/i18n/fr.po
  auth_admin_passkey/i18n/fr_CH.po
  auth_admin_passkey/i18n/fr_FR.po
  auth_admin_passkey/i18n/hr.po
  auth_admin_passkey/i18n/hr_HR.po
  auth_admin_passkey/i18n/it.po
  auth_admin_passkey/i18n/nl.po
  auth_admin_passkey/i18n/nl_NL.po
  auth_admin_passkey/i18n/pt.po
  auth_admin_passkey/i18n/pt_BR.po
  auth_admin_passkey/i18n/ro.po
  auth_admin_passkey/i18n/sl.po
  auth_admin_passkey/i18n/tr.po
  auth_admin_passkey/i18n/tr_TR.po
  auth_admin_passkey/i18n/zh_CN.po
  auth_admin_passkey/models/__init__.py
  auth_admin_passkey/models/res_users.py
  auth_admin_passkey/readme/CONFIGURE.rst
  auth_admin_passkey/readme/CONTRIBUTORS.rst
  auth_admin_passkey/readme/DESCRIPTION.rst
  auth_admin_passkey/static/description/icon.png
  auth_admin_passkey/static/description/index.html
  auth_admin_passkey/tests/__init__.py
  auth_admin_passkey/tests/test_auth_admin_passkey.py
  auth_admin_passkey/tests/test_ui.py
  setup/auth_admin_passkey/odoo/addons/auth_admin_passkey
  setup/auth_admin_passkey/setup.py
Labels: approved, ready to merge, bot is merging ⏳, no stale

#444 [16.0][MIG] base_user_show_email
  base_user_show_email/README.rst
  base_user_show_email/__init__.py
  base_user_show_email/__manifest__.py
  base_user_show_email/i18n/base_user_show_email.pot
  base_user_show_email/readme/CONTRIBUTORS.rst
  base_user_show_email/readme/DESCRIPTION.rst
  base_user_show_email/static/description/icon.png
  base_user_show_email/static/description/index.html
  base_user_show_email/views/login_layout.xml
  base_user_show_email/views/res_users_view.xml
  setup/base_user_show_email/odoo/addons/base_user_show_email
  setup/base_user_show_email/setup.py
Labels: approved, bot is merging ⏳

#446 [MIG] auth_signup_verify_email: Migration to 16.0
  auth_signup_verify_email/README.rst
  auth_signup_verify_email/__init__.py
  auth_signup_verify_email/__manifest__.py
  auth_signup_verify_email/controllers/__init__.py
  auth_signup_verify_email/controllers/main.py
  auth_signup_verify_email/i18n/ar.po
  auth_signup_verify_email/i18n/auth_signup_verify_email.pot
  auth_signup_verify_email/i18n/de.po
  auth_signup_verify_email/i18n/es.po
  auth_signup_verify_email/i18n/fr.po
  auth_signup_verify_email/i18n/hr.po
  auth_signup_verify_email/i18n/hr_HR.po
  auth_signup_verify_email/i18n/it.po
  auth_signup_verify_email/i18n/pt_BR.po
  auth_signup_verify_email/i18n/ro.po
  auth_signup_verify_email/i18n/sl.po
  auth_signup_verify_email/i18n/tr.po
  auth_signup_verify_email/readme/CONFIGURE.rst
  auth_signup_verify_email/readme/CONTRIBUTORS.rst
  auth_signup_verify_email/readme/DESCRIPTION.rst
  auth_signup_verify_email/readme/INSTALL.rst
  auth_signup_verify_email/readme/USAGE.rst
  auth_signup_verify_email/static/description/icon.png
  auth_signup_verify_email/static/description/icon.svg
  auth_signup_verify_email/static/description/index.html
  auth_signup_verify_email/tests/__init__.py
  auth_signup_verify_email/tests/test_verify_email.py
  auth_signup_verify_email/views/signup.xml
  requirements.txt
  setup/auth_signup_verify_email/odoo/addons/auth_signup_verify_email
  setup/auth_signup_verify_email/setup.py
Labels: approved, bot is merging ⏳

#479 [16.0][MIG] auth_user_case_insensitive
  auth_user_case_insensitive/README.rst
  auth_user_case_insensitive/__init__.py
  auth_user_case_insensitive/__manifest__.py
  auth_user_case_insensitive/hooks.py
  auth_user_case_insensitive/i18n/ar.po
  auth_user_case_insensitive/i18n/auth_user_case_insensitive.pot
  auth_user_case_insensitive/i18n/ca.po
  auth_user_case_insensitive/i18n/da.po
  auth_user_case_insensitive/i18n/de.po
  auth_user_case_insensitive/i18n/el_GR.po
  auth_user_case_insensitive/i18n/es.po
  auth_user_case_insensitive/i18n/es_ES.po
  auth_user_case_insensitive/i18n/fi.po
  auth_user_case_insensitive/i18n/fr.po
  auth_user_case_insensitive/i18n/fr_CH.po
  auth_user_case_insensitive/i18n/fr_FR.po
  auth_user_case_insensitive/i18n/hr.po
  auth_user_case_insensitive/i18n/hr_HR.po
  auth_user_case_insensitive/i18n/it.po
  auth_user_case_insensitive/i18n/lt.po
  auth_user_case_insensitive/i18n/nl.po
  auth_user_case_insensitive/i18n/nl_NL.po
  auth_user_case_insensitive/i18n/pt.po
  auth_user_case_insensitive/i18n/pt_BR.po
  auth_user_case_insensitive/i18n/ro.po
  auth_user_case_insensitive/i18n/sl.po
  auth_user_case_insensitive/i18n/tr.po
  auth_user_case_insensitive/i18n/tr_TR.po
  auth_user_case_insensitive/i18n/zh_CN.po
  auth_user_case_insensitive/models/__init__.py
  auth_user_case_insensitive/models/res_users.py
  auth_user_case_insensitive/readme/CONTRIBUTORS.rst
  auth_user_case_insensitive/readme/DESCRIPTION.rst
  auth_user_case_insensitive/readme/INSTALL.rst
  auth_user_case_insensitive/readme/USAGE.rst
  auth_user_case_insensitive/static/description/icon.png
  auth_user_case_insensitive/static/description/index.html
  auth_user_case_insensitive/tests/__init__.py
  auth_user_case_insensitive/tests/test_res_users.py
  setup/auth_user_case_insensitive/odoo/addons/auth_user_case_insensitive
  setup/auth_user_case_insensitive/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#531 [14.0][MIG] backport `auth_jwt` and `auth_jwt_demo` improvements from 16.0
  auth_jwt/__manifest__.py
  auth_jwt/exceptions.py
  auth_jwt/models/auth_jwt_validator.py
  auth_jwt/models/ir_http.py
  auth_jwt/readme/USAGE.rst
  auth_jwt/tests/test_auth_jwt.py
  auth_jwt/views/auth_jwt_validator_views.xml
  auth_jwt_demo/controllers/main.py
  auth_jwt_demo/demo/auth_jwt_validator.xml
  auth_jwt_demo/tests/test_auth_jwt_demo.py
Labels: approved, bot is merging ⏳

#540 [FIX] vault: Vault re-encryption in a single transaction
  vault/controllers/main.py
  vault/models/abstract_vault_field.py
  vault/models/vault.py
  vault/models/vault_entry.py
  vault/models/vault_right.py
  vault/static/src/legacy/vault_controller.js
  vault/tests/test_controller.py
  vault/tests/test_rights.py
  vault/views/vault_views.xml
Labels: approved, bot is merging ⏳
