Repository OCA/server-auth, pull requests merged in 2023-11, with the labels that each got.

#436 [12.0] auth_oidc: fixes
  auth_oidc/__manifest__.py
  auth_oidc/models/auth_oauth_provider.py
  auth_oidc/models/res_users.py
  auth_oidc/readme/CONTRIBUTORS.rst
  auth_oidc/readme/HISTORY.rst
  auth_oidc/tests/test_auth_oidc_auth_code.py
Labels: approved, no stale

#577 [13.0] auth_oidc fixes
  auth_oidc/__manifest__.py
  auth_oidc/models/auth_oauth_provider.py
  auth_oidc/models/res_users.py
  auth_oidc/readme/CONTRIBUTORS.rst
  auth_oidc/readme/HISTORY.rst
  auth_oidc/tests/test_auth_oidc_auth_code.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#578 [17.0][MIG] auth_admin_passkey
  auth_admin_passkey/README.rst
  auth_admin_passkey/__init__.py
  auth_admin_passkey/__manifest__.py
  auth_admin_passkey/i18n/ar.po
  auth_admin_passkey/i18n/auth_admin_passkey.pot
  auth_admin_passkey/i18n/ca.po
  auth_admin_passkey/i18n/da.po
  auth_admin_passkey/i18n/de.po
  auth_admin_passkey/i18n/el_GR.po
  auth_admin_passkey/i18n/es.po
  auth_admin_passkey/i18n/es_ES.po
  auth_admin_passkey/i18n/fi.po
  auth_admin_passkey/i18n/fr.po
  auth_admin_passkey/i18n/fr_CH.po
  auth_admin_passkey/i18n/fr_FR.po
  auth_admin_passkey/i18n/hr.po
  auth_admin_passkey/i18n/hr_HR.po
  auth_admin_passkey/i18n/it.po
  auth_admin_passkey/i18n/nl.po
  auth_admin_passkey/i18n/nl_NL.po
  auth_admin_passkey/i18n/pt.po
  auth_admin_passkey/i18n/pt_BR.po
  auth_admin_passkey/i18n/ro.po
  auth_admin_passkey/i18n/sl.po
  auth_admin_passkey/i18n/tr.po
  auth_admin_passkey/i18n/tr_TR.po
  auth_admin_passkey/i18n/zh_CN.po
  auth_admin_passkey/models/__init__.py
  auth_admin_passkey/models/res_users.py
  auth_admin_passkey/pyproject.toml
  auth_admin_passkey/readme/CONFIGURE.md
  auth_admin_passkey/readme/CONTRIBUTORS.md
  auth_admin_passkey/readme/DESCRIPTION.md
  auth_admin_passkey/static/description/icon.png
  auth_admin_passkey/static/description/index.html
  auth_admin_passkey/tests/__init__.py
  auth_admin_passkey/tests/test_auth_admin_passkey.py
  auth_admin_passkey/tests/test_ui.py
Labels: approved, ready to merge, bot is merging ⏳

#582 [16.0] auth_jwt_demo: add test
  auth_jwt_demo/tests/test_auth_jwt_demo.py
Labels: bot is merging ⏳

#581 [16.0][ADD] auth_jwt_server_env
  .copier-answers.yml
  .github/workflows/test.yml
  auth_jwt_server_env/README.rst
  auth_jwt_server_env/__init__.py
  auth_jwt_server_env/__manifest__.py
  auth_jwt_server_env/models/__init__.py
  auth_jwt_server_env/models/auth_jwt_validator.py
  auth_jwt_server_env/readme/CONTRIBUTORS.rst
  auth_jwt_server_env/readme/DESCRIPTION.rst
  auth_jwt_server_env/static/description/index.html
  setup/auth_jwt_server_env/odoo/addons/auth_jwt_server_env
  setup/auth_jwt_server_env/setup.py
Labels: approved, bot is merging ⏳
