Repository OCA/server-auth, pull requests merged in 2023-09, with the labels that each got.

#525 [16][MIG] auth_api_key_server_env #455
  auth_api_key_server_env/README.rst
  auth_api_key_server_env/__init__.py
  auth_api_key_server_env/__manifest__.py
  auth_api_key_server_env/i18n/auth_api_key_server_env.pot
  auth_api_key_server_env/migrations/16.0.1.0.0/post-migration.py
  auth_api_key_server_env/models/__init__.py
  auth_api_key_server_env/models/auth_api_key.py
  auth_api_key_server_env/readme/CONTRIBUTORS.rst
  auth_api_key_server_env/readme/DESCRIPTION.rst
  auth_api_key_server_env/static/description/icon.png
  auth_api_key_server_env/static/description/index.html
  auth_api_key_server_env/tests/__init__.py
  auth_api_key_server_env/tests/test_auth_api_key.py
  setup/auth_api_key_server_env/odoo/addons/auth_api_key_server_env
  setup/auth_api_key_server_env/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#481 [15.0][ADD] auth_saml: Improve login page
  auth_saml/__manifest__.py
  auth_saml/controllers/main.py
  auth_saml/models/auth_saml_provider.py
  auth_saml/readme/CONTRIBUTORS.rst
  auth_saml/views/auth_saml.xml
Labels: bot is merging ⏳

#483 [15.0][ADD] auth_saml: handle redirect parameter in the URI
  auth_saml/controllers/main.py
  auth_saml/models/auth_saml_provider.py
  auth_saml/readme/HISTORY.rst
  auth_saml/tests/test_pysaml.py
  auth_saml/views/auth_saml.xml
Labels: bot is merging ⏳

#507 [16.0][MIG] auth_session_timeout
  auth_session_timeout/README.rst
  auth_session_timeout/__init__.py
  auth_session_timeout/__manifest__.py
  auth_session_timeout/data/ir_config_parameter_data.xml
  auth_session_timeout/i18n/ar.po
  auth_session_timeout/i18n/auth_session_timeout.pot
  auth_session_timeout/i18n/ca.po
  auth_session_timeout/i18n/da.po
  auth_session_timeout/i18n/de.po
  auth_session_timeout/i18n/el_GR.po
  auth_session_timeout/i18n/es.po
  auth_session_timeout/i18n/es_ES.po
  auth_session_timeout/i18n/fi.po
  auth_session_timeout/i18n/fr.po
  auth_session_timeout/i18n/fr_CH.po
  auth_session_timeout/i18n/fr_FR.po
  auth_session_timeout/i18n/hr.po
  auth_session_timeout/i18n/hr_HR.po
  auth_session_timeout/i18n/it.po
  auth_session_timeout/i18n/nl.po
  auth_session_timeout/i18n/nl_NL.po
  auth_session_timeout/i18n/pt.po
  auth_session_timeout/i18n/pt_BR.po
  auth_session_timeout/i18n/ro.po
  auth_session_timeout/i18n/sl.po
  auth_session_timeout/i18n/tr.po
  auth_session_timeout/i18n/tr_TR.po
  auth_session_timeout/i18n/zh_CN.po
  auth_session_timeout/models/__init__.py
  auth_session_timeout/models/ir_config_parameter.py
  auth_session_timeout/models/ir_http.py
  auth_session_timeout/models/res_users.py
  auth_session_timeout/readme/CONFIGURE.rst
  auth_session_timeout/readme/CONTRIBUTORS.rst
  auth_session_timeout/readme/DESCRIPTION.rst
  auth_session_timeout/readme/USAGE.rst
  auth_session_timeout/static/description/icon.png
  auth_session_timeout/static/description/index.html
  auth_session_timeout/tests/__init__.py
  auth_session_timeout/tests/test_ir_config_parameter.py
  auth_session_timeout/tests/test_res_users.py
  setup/auth_session_timeout/odoo/addons/auth_session_timeout
  setup/auth_session_timeout/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#500 [IMP] password_security: add flag to enable/disable password security policy
  password_security/__manifest__.py
  password_security/migrations/15.0.1.2.0/post-migration.py
  password_security/models/res_company.py
  password_security/models/res_config_settings.py
  password_security/models/res_users.py
  password_security/tests/test_password_history.py
  password_security/tests/test_password_security_home.py
  password_security/tests/test_res_users.py
  password_security/tests/test_reset_password.py
  password_security/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#554 [16.0][MIG] users_ldap_groups: Migration to version 16.0
  setup/users_ldap_groups/odoo/addons/users_ldap_groups
  setup/users_ldap_groups/setup.py
  users_ldap_groups/README.rst
  users_ldap_groups/__init__.py
  users_ldap_groups/__manifest__.py
  users_ldap_groups/i18n/de.po
  users_ldap_groups/i18n/es.po
  users_ldap_groups/i18n/fr.po
  users_ldap_groups/i18n/hr.po
  users_ldap_groups/i18n/it.po
  users_ldap_groups/i18n/pt_BR.po
  users_ldap_groups/i18n/sl.po
  users_ldap_groups/i18n/users_ldap_groups.pot
  users_ldap_groups/models/__init__.py
  users_ldap_groups/models/res_company_ldap.py
  users_ldap_groups/models/res_company_ldap_group_mapping.py
  users_ldap_groups/models/res_company_ldap_operator.py
  users_ldap_groups/models/res_users.py
  users_ldap_groups/readme/CONTRIBUTORS.rst
  users_ldap_groups/readme/DESCRIPTION.rst
  users_ldap_groups/readme/USAGE.rst
  users_ldap_groups/security/ir.model.access.csv
  users_ldap_groups/static/description/icon.png
  users_ldap_groups/static/description/index.html
  users_ldap_groups/tests/__init__.py
  users_ldap_groups/tests/test_users_ldap_groups.py
  users_ldap_groups/views/res_company_ldap_views.xml
Labels: approved, bot is merging ⏳
