Repository OCA/server-auth, pull requests merged in 2024-09, with the labels that each got.

#684 [17.0][FIX] impersonate_login: fix computed body field
  impersonate_login/models/mail_message.py
Labels: approved, bot is merging ⏳

#683 [16.0][MIG] impersonate_login: backport from V17 to V16
  impersonate_login/README.rst
  impersonate_login/__init__.py
  impersonate_login/__manifest__.py
  impersonate_login/hooks.py
  impersonate_login/i18n/impersonate_login.pot
  impersonate_login/models/__init__.py
  impersonate_login/models/impersonate_log.py
  impersonate_login/models/ir_http.py
  impersonate_login/models/mail_message.py
  impersonate_login/models/mail_thread.py
  impersonate_login/models/model.py
  impersonate_login/models/res_users.py
  impersonate_login/readme/CONFIGURE.md
  impersonate_login/readme/CONTRIBUTORS.md
  impersonate_login/readme/DESCRIPTION.md
  impersonate_login/readme/USAGE.md
  impersonate_login/security/group.xml
  impersonate_login/security/ir.model.access.csv
  impersonate_login/static/description/icon.png
  impersonate_login/static/description/index.html
  impersonate_login/static/src/js/user_menu.esm.js
  impersonate_login/tests/__init__.py
  impersonate_login/tests/test_impersonate_login.py
  impersonate_login/views/impersonate_log.xml
  impersonate_login/views/res_users.xml
  setup/impersonate_login/odoo/addons/impersonate_login
  setup/impersonate_login/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#666 [14.0][IMP] auth_oidc: Logout the user from the auth provider
  auth_oidc/controllers/main.py
  auth_oidc/models/auth_oauth_provider.py
  auth_oidc/tests/__init__.py
  auth_oidc/tests/test_auth_oidc_logout.py
  auth_oidc/views/auth_oauth_provider.xml
Labels: approved, ready to merge, bot is merging ⏳

#689 [FIX] auth_session_timeout: add /longpolling/im_status as ignored url
  auth_session_timeout/__manifest__.py
  auth_session_timeout/data/ir_config_parameter_data.xml
  auth_session_timeout/migrations/15.0.1.0.1/post-migration.py
Labels: approved, bot is merging ⏳

#640 [15.0][FIX] auth_saml: do not force using vulnerable cryptography module
  auth_saml/__manifest__.py
  auth_saml/readme/INSTALL.rst
  requirements.txt
  test-requirements.txt
Labels: bot is merging ⏳

#690 [FIX] password_security: Fix reset password when user doesn't have password_write_date value.
  password_security/models/res_users.py
Labels: approved, bot is merging ⏳

#596 [16.0][FIX] users_ldap_groups: safe LDAP decode
  users_ldap_groups/models/res_company_ldap_operator.py
  users_ldap_groups/tests/test_users_ldap_groups.py
Labels: approved, bot is merging ⏳
