Repository OCA/server-auth, pull requests merged in 2024-10, with the labels that each got.

#704 [17.0] auth_api_key_group: Port from 14.0
  auth_api_key_group/README.rst
  auth_api_key_group/__manifest__.py
  auth_api_key_group/models/auth_api_key.py
  auth_api_key_group/models/auth_api_key_group.py
  auth_api_key_group/static/description/index.html
  auth_api_key_group/tests/test_auth_api_key_group.py
Labels: bot is merging ⏳

#700 [17.0][PW] auth_api_key: Port from 14.0
  auth_api_key/__manifest__.py
  auth_api_key/models/__init__.py
  auth_api_key/models/auth_api_key.py
  auth_api_key/models/res_company.py
  auth_api_key/models/res_config_settings.py
  auth_api_key/tests/test_auth_api_key.py
  auth_api_key/views/auth_api_key.xml
  auth_api_key/views/res_config_settings.xml
Labels: bot is merging ⏳

#699 [18.0][MIG] base_user_empty_password
  base_user_empty_password/README.rst
  base_user_empty_password/__init__.py
  base_user_empty_password/__manifest__.py
  base_user_empty_password/i18n/base_user_empty_password.pot
  base_user_empty_password/models/__init__.py
  base_user_empty_password/models/res_users.py
  base_user_empty_password/pyproject.toml
  base_user_empty_password/readme/CONTRIBUTORS.md
  base_user_empty_password/readme/CREDITS.md
  base_user_empty_password/readme/DESCRIPTION.md
  base_user_empty_password/security/ir.model.access.csv
  base_user_empty_password/static/description/icon.png
  base_user_empty_password/static/description/index.html
  base_user_empty_password/tests/__init__.py
  base_user_empty_password/tests/test_user_empty_password.py
  base_user_empty_password/views/res_users.xml
  base_user_empty_password/wizard/__init__.py
  base_user_empty_password/wizard/empty_password.py
  base_user_empty_password/wizard/empty_password.xml
Labels: bot is merging ⏳

#701 [18.0][MIG] auth_api_key: Migration to 18.0
  auth_api_key/README.rst
  auth_api_key/__init__.py
  auth_api_key/__manifest__.py
  auth_api_key/i18n/auth_api_key.pot
  auth_api_key/i18n/it.po
  auth_api_key/models/__init__.py
  auth_api_key/models/auth_api_key.py
  auth_api_key/models/ir_http.py
  auth_api_key/models/res_company.py
  auth_api_key/models/res_config_settings.py
  auth_api_key/pyproject.toml
  auth_api_key/readme/CONFIGURE.md
  auth_api_key/readme/CONTRIBUTORS.md
  auth_api_key/readme/CREDITS.md
  auth_api_key/readme/DESCRIPTION.md
  auth_api_key/readme/USAGE.md
  auth_api_key/security/ir.model.access.csv
  auth_api_key/static/description/icon.png
  auth_api_key/static/description/index.html
  auth_api_key/tests/__init__.py
  auth_api_key/tests/test_auth_api_key.py
  auth_api_key/views/auth_api_key.xml
  auth_api_key/views/res_config_settings.xml
Labels: bot is merging ⏳

#709 [17.0][UDP] auth_api_key: Update description for reason to keep this module
  auth_api_key/readme/DESCRIPTION.md
Labels: bot is merging ⏳

#703 [18.0][MIG] auth_api_key_group: Migration to 18.0
  auth_api_key_group/README.rst
  auth_api_key_group/__init__.py
  auth_api_key_group/__manifest__.py
  auth_api_key_group/i18n/auth_api_key_group.pot
  auth_api_key_group/i18n/it.po
  auth_api_key_group/models/__init__.py
  auth_api_key_group/models/auth_api_key.py
  auth_api_key_group/models/auth_api_key_group.py
  auth_api_key_group/pyproject.toml
  auth_api_key_group/readme/CONTRIBUTORS.md
  auth_api_key_group/readme/CREDITS.md
  auth_api_key_group/readme/DESCRIPTION.md
  auth_api_key_group/security/ir.model.access.csv
  auth_api_key_group/static/description/icon.png
  auth_api_key_group/static/description/index.html
  auth_api_key_group/tests/__init__.py
  auth_api_key_group/tests/test_auth_api_key_group.py
  auth_api_key_group/views/auth_api_key_group_view.xml
  auth_api_key_group/views/auth_api_key_view.xml
Labels: bot is merging ⏳

#686 [17.0][FIX] impersonate_login: fix user_id comodel_name
  impersonate_login/models/impersonate_log.py
Labels: approved, ready to merge, bot is merging ⏳

#702 [18.0][MIG] auth_api_key_server_env: Migration to 18.0
  auth_api_key_server_env/README.rst
  auth_api_key_server_env/__init__.py
  auth_api_key_server_env/__manifest__.py
  auth_api_key_server_env/i18n/auth_api_key_server_env.pot
  auth_api_key_server_env/i18n/it.po
  auth_api_key_server_env/models/__init__.py
  auth_api_key_server_env/models/auth_api_key.py
  auth_api_key_server_env/pyproject.toml
  auth_api_key_server_env/readme/CONTRIBUTORS.md
  auth_api_key_server_env/readme/CREDITS.md
  auth_api_key_server_env/readme/DESCRIPTION.md
  auth_api_key_server_env/static/description/icon.png
  auth_api_key_server_env/static/description/index.html
  auth_api_key_server_env/tests/__init__.py
  auth_api_key_server_env/tests/test_auth_api_key.py
Labels: bot is merging ⏳

#595 [DOC]Add option to configure keycloak
  auth_oidc/readme/CONFIGURE.md
Labels: bot is merging ⏳, stale

#706 [17.0][PORT] auth_oidc: prompt for account on AAD login
  auth_oidc/README.rst
  auth_oidc/controllers/main.py
  auth_oidc/data/auth_oauth_data.xml
  auth_oidc/demo/local_keycloak.xml
  auth_oidc/models/auth_oauth_provider.py
  auth_oidc/readme/CONFIGURE.md
  auth_oidc/static/description/index.html
  auth_oidc/static/description/oauth-microsoft_azure-select_account.png
  auth_oidc/tests/test_auth_oidc_auth_code.py
  auth_oidc/views/auth_oauth_provider.xml
Labels: approved, bot is merging ⏳

#646 [17.0][MIG] auth_session_timeout: Migration to 17.0
  auth_session_timeout/README.rst
  auth_session_timeout/__init__.py
  auth_session_timeout/__manifest__.py
  auth_session_timeout/data/ir_config_parameter_data.xml
  auth_session_timeout/i18n/ar.po
  auth_session_timeout/i18n/auth_session_timeout.pot
  auth_session_timeout/i18n/ca.po
  auth_session_timeout/i18n/da.po
  auth_session_timeout/i18n/de.po
  auth_session_timeout/i18n/el_GR.po
  auth_session_timeout/i18n/es.po
  auth_session_timeout/i18n/es_ES.po
  auth_session_timeout/i18n/fi.po
  auth_session_timeout/i18n/fr.po
  auth_session_timeout/i18n/fr_CH.po
  auth_session_timeout/i18n/fr_FR.po
  auth_session_timeout/i18n/hr.po
  auth_session_timeout/i18n/hr_HR.po
  auth_session_timeout/i18n/it.po
  auth_session_timeout/i18n/nl.po
  auth_session_timeout/i18n/nl_NL.po
  auth_session_timeout/i18n/pt.po
  auth_session_timeout/i18n/pt_BR.po
  auth_session_timeout/i18n/ro.po
  auth_session_timeout/i18n/sl.po
  auth_session_timeout/i18n/tr.po
  auth_session_timeout/i18n/tr_TR.po
  auth_session_timeout/i18n/zh_CN.po
  auth_session_timeout/migrations/17.0.1.0.0/pre-migration.py
  auth_session_timeout/models/__init__.py
  auth_session_timeout/models/ir_config_parameter.py
  auth_session_timeout/models/ir_http.py
  auth_session_timeout/models/res_users.py
  auth_session_timeout/pyproject.toml
  auth_session_timeout/readme/CONFIGURE.md
  auth_session_timeout/readme/CONTRIBUTORS.md
  auth_session_timeout/readme/DESCRIPTION.md
  auth_session_timeout/readme/USAGE.md
  auth_session_timeout/static/description/icon.png
  auth_session_timeout/static/description/index.html
  auth_session_timeout/tests/__init__.py
  auth_session_timeout/tests/test_ir_config_parameter.py
  auth_session_timeout/tests/test_res_users.py
Labels: approved, bot is merging ⏳
