Repository OCA/server-auth, pull requests merged in 2024-08, with the labels that each got.

#672 [16.0][IMP] vault: Update value when input is decrypted
  vault/static/src/backend/controller.esm.js
  vault/static/src/backend/fields/vault_field.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#603 [14.0] [MIG] auth_oauth_autologin
  auth_oauth_autologin/README.rst
  auth_oauth_autologin/__init__.py
  auth_oauth_autologin/__manifest__.py
  auth_oauth_autologin/controllers/__init__.py
  auth_oauth_autologin/controllers/main.py
  auth_oauth_autologin/i18n/auth_oauth_autologin.pot
  auth_oauth_autologin/models/__init__.py
  auth_oauth_autologin/models/auth_oauth_provider.py
  auth_oauth_autologin/readme/CONFIGURE.rst
  auth_oauth_autologin/readme/DESCRIPTION.rst
  auth_oauth_autologin/readme/USAGE.rst
  auth_oauth_autologin/static/description/icon.png
  auth_oauth_autologin/static/description/index.html
  auth_oauth_autologin/tests/__init__.py
  auth_oauth_autologin/tests/test_auth_oauth_autologin.py
  auth_oauth_autologin/views/auth_oauth_provider.xml
  setup/auth_oauth_autologin/odoo/addons/auth_oauth_autologin
  setup/auth_oauth_autologin/setup.py
Labels: needs review, bot is merging ⏳, no stale

#650 [Fix] auth_oidc: move tenant id config step in readme
  auth_oidc/readme/CONFIGURE.md
Labels: bot is merging ⏳

#679 [16.0][FIX] vault_share: Button to share value not showed and not working
  vault_share/static/src/backend/fields/vault_field.esm.js
Labels: approved, bot is merging ⏳

#634 [17.0][MIG] auth_saml
  auth_saml/README.rst
  auth_saml/__init__.py
  auth_saml/__manifest__.py
  auth_saml/controllers/__init__.py
  auth_saml/controllers/main.py
  auth_saml/data/ir_config_parameter.xml
  auth_saml/i18n/auth_saml.pot
  auth_saml/i18n/es.po
  auth_saml/i18n/fr.po
  auth_saml/i18n/it.po
  auth_saml/models/__init__.py
  auth_saml/models/auth_saml_attribute_mapping.py
  auth_saml/models/auth_saml_provider.py
  auth_saml/models/auth_saml_request.py
  auth_saml/models/ir_config_parameter.py
  auth_saml/models/res_config_settings.py
  auth_saml/models/res_users.py
  auth_saml/models/res_users_saml.py
  auth_saml/pyproject.toml
  auth_saml/readme/CONFIGURE.md
  auth_saml/readme/CONTRIBUTORS.md
  auth_saml/readme/DESCRIPTION.md
  auth_saml/readme/HISTORY.md
  auth_saml/readme/INSTALL.md
  auth_saml/readme/ROADMAP.md
  auth_saml/readme/USAGE.md
  auth_saml/security/ir.model.access.csv
  auth_saml/static/description/icon.png
  auth_saml/static/description/index.html
  auth_saml/tests/__init__.py
  auth_saml/tests/data/idp.pem
  auth_saml/tests/data/sp.key
  auth_saml/tests/data/sp.pem
  auth_saml/tests/fake_idp.py
  auth_saml/tests/test_models_saml_attribute_mapping.py
  auth_saml/tests/test_pysaml.py
  auth_saml/views/auth_saml.xml
  auth_saml/views/res_config_settings.xml
  auth_saml/views/res_users.xml
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#681 [17.0][MIG] auth_signup_verify_email: Migration to 17.0
  auth_signup_verify_email/README.rst
  auth_signup_verify_email/__init__.py
  auth_signup_verify_email/__manifest__.py
  auth_signup_verify_email/controllers/__init__.py
  auth_signup_verify_email/controllers/main.py
  auth_signup_verify_email/i18n/ar.po
  auth_signup_verify_email/i18n/auth_signup_verify_email.pot
  auth_signup_verify_email/i18n/de.po
  auth_signup_verify_email/i18n/es.po
  auth_signup_verify_email/i18n/fr.po
  auth_signup_verify_email/i18n/hr.po
  auth_signup_verify_email/i18n/hr_HR.po
  auth_signup_verify_email/i18n/it.po
  auth_signup_verify_email/i18n/pt_BR.po
  auth_signup_verify_email/i18n/ro.po
  auth_signup_verify_email/i18n/sl.po
  auth_signup_verify_email/i18n/tr.po
  auth_signup_verify_email/pyproject.toml
  auth_signup_verify_email/readme/CONFIGURE.md
  auth_signup_verify_email/readme/CONTRIBUTORS.md
  auth_signup_verify_email/readme/DESCRIPTION.md
  auth_signup_verify_email/readme/INSTALL.md
  auth_signup_verify_email/readme/USAGE.md
  auth_signup_verify_email/static/description/icon.png
  auth_signup_verify_email/static/description/icon.svg
  auth_signup_verify_email/static/description/index.html
  auth_signup_verify_email/tests/__init__.py
  auth_signup_verify_email/tests/test_verify_email.py
  auth_signup_verify_email/views/signup.xml
  requirements.txt
Labels: bot is merging ⏳

#680 [17.0][MIG] impersonate_login
  impersonate_login/README.rst
  impersonate_login/__init__.py
  impersonate_login/__manifest__.py
  impersonate_login/hooks.py
  impersonate_login/models/__init__.py
  impersonate_login/models/impersonate_log.py
  impersonate_login/models/ir_http.py
  impersonate_login/models/mail_message.py
  impersonate_login/models/mail_thread.py
  impersonate_login/models/model.py
  impersonate_login/models/res_users.py
  impersonate_login/pyproject.toml
  impersonate_login/readme/CONFIGURE.md
  impersonate_login/readme/CONTRIBUTORS.md
  impersonate_login/readme/DESCRIPTION.md
  impersonate_login/readme/USAGE.md
  impersonate_login/security/group.xml
  impersonate_login/security/ir.model.access.csv
  impersonate_login/static/description/index.html
  impersonate_login/static/src/js/user_menu.esm.js
  impersonate_login/tests/__init__.py
  impersonate_login/tests/test_impersonate_login.py
  impersonate_login/views/impersonate_log.xml
  impersonate_login/views/res_users.xml
Labels: approved, ready to merge, bot is merging ⏳
