Repository OCA/server-auth, pull requests merged in 2024-06, with the labels that each got.

#659 [16.0][FIX] users_ldap_groups JSON RPC vulnerability
  users_ldap_groups/models/res_company_ldap.py
  users_ldap_groups/models/res_company_ldap_operator.py
Labels: approved

#661 [14.0][PORT] 659 from 16.0
  users_ldap_groups/models/res_company_ldap.py
  users_ldap_groups/models/res_company_ldap_operator.py
Labels: approved, bot is merging ⏳

#662 [13.0][PORT] 659 from 16.0
  users_ldap_groups/models/res_company_ldap.py
  users_ldap_groups/models/res_company_ldap_operator.py
Labels: approved, bot is merging ⏳

#660 [15.0][PORT] 659 from 16.0
  users_ldap_groups/models/res_company_ldap.py
  users_ldap_groups/models/res_company_ldap_operator.py
Labels: approved, bot is merging ⏳

#642 [FIX][14.0] auth_saml: Fix logic of SELECT FOR UDPDATE to only lock records that will be updated
  auth_saml/models/auth_saml_provider.py
Labels: approved, bot is merging ⏳

#667 [16.0][FIX] auth_saml: update signin method
  auth_saml/controllers/main.py
  auth_saml/tests/test_pysaml.py
Labels: bot is merging ⏳

#663 [16.0][FIX] vault: Secret generator is not saving new value
  vault/README.rst
  vault/readme/CONTRIBUTORS.rst
  vault/static/description/index.html
  vault/static/src/common/utils.esm.js
Labels: approved, bot is merging ⏳

#665 [16.0][FIX] vault: Stop propagation when clicking "enter"
  vault/static/src/common/utils.esm.js
Labels: approved, bot is merging ⏳
