Repository OCA/server-auth, pull requests merged in 2024-05, with the labels that each got.

#638 [14.0] Add module base_user_empty_password
  base_user_empty_password/__init__.py
  base_user_empty_password/__manifest__.py
  base_user_empty_password/models/__init__.py
  base_user_empty_password/models/res_users.py
  base_user_empty_password/readme/CONTRIBUTORS.md
  base_user_empty_password/readme/DESCRIPTION.md
  base_user_empty_password/security/ir.model.access.csv
  base_user_empty_password/views/res_users.xml
  base_user_empty_password/wizard/__init__.py
  base_user_empty_password/wizard/empty_password.py
  base_user_empty_password/wizard/empty_password.xml
  setup/base_user_empty_password/odoo/addons/base_user_empty_password
  setup/base_user_empty_password/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#644 [15.0][FIX] password_security: fix Policy applied to reset password dialog
  password_security/README.rst
  password_security/__manifest__.py
  password_security/controllers/main.py
  password_security/readme/CONTRIBUTORS.rst
  password_security/static/description/index.html
  password_security/static/src/js/signup_policy.js
  password_security/views/signup_templates.xml
Labels: approved, bot is merging ⏳

#602 [IMP] auth_saml: download the provider metadata
  auth_saml/README.rst
  auth_saml/models/auth_saml_provider.py
  auth_saml/readme/CONFIGURE.rst
  auth_saml/tests/data/cert_idp_expired.pem
  auth_saml/tests/data/key_idp_expired.pem
  auth_saml/tests/fake_idp.py
  auth_saml/tests/test_pysaml.py
  auth_saml/views/auth_saml.xml
Labels: bot is merging ⏳

#639 [15.0] password_security: Fix login with MFA enabled
  password_security/controllers/main.py
  password_security/tests/test_password_security_home.py
Labels: approved, ready to merge, bot is merging ⏳
