Repository OCA/server-auth, pull requests merged in 2024-03, with the labels that each got.

#570 14.0 backport auth OIDC environment
  auth_oidc_environment/README.rst
  auth_oidc_environment/__init__.py
  auth_oidc_environment/__manifest__.py
  auth_oidc_environment/i18n/auth_oidc_environment.pot
  auth_oidc_environment/models/__init__.py
  auth_oidc_environment/models/auth_oauth_provider.py
  auth_oidc_environment/readme/CONFIGURE.rst
  auth_oidc_environment/readme/CONTRIBUTORS.rst
  auth_oidc_environment/readme/DESCRIPTION.rst
  auth_oidc_environment/readme/USAGE.rst
  auth_oidc_environment/static/description/icon.png
  auth_oidc_environment/static/description/index.html
  auth_oidc_environment/tests/__init__.py
  auth_oidc_environment/tests/test_auth_oidc_environment.py
  setup/auth_oidc_environment/odoo/addons/auth_oidc_environment
  setup/auth_oidc_environment/setup.py
Labels: approved, bot is merging ⏳, stale

#618 [16.0] auth_oidc: OpenID Connect fixes from 15.0
  auth_oidc/README.rst
  auth_oidc/__manifest__.py
  auth_oidc/models/auth_oauth_provider.py
  auth_oidc/models/res_users.py
  auth_oidc/readme/CONTRIBUTORS.md
  auth_oidc/readme/HISTORY.md
  auth_oidc/static/description/index.html
  auth_oidc/tests/test_auth_oidc_auth_code.py
  test-requirements.txt
Labels: bot is merging ⏳

#511 [13.0][CHG] auth_oauth_autologin: redirect to the oauth in JS to keep track of the fragment
  auth_oauth_autologin/__manifest__.py
  auth_oauth_autologin/controllers/main.py
  auth_oauth_autologin/static/src/js/web_login.js
  auth_oauth_autologin/tests/__init__.py
  auth_oauth_autologin/tests/test_auth_oauth_autologin.py
  auth_oauth_autologin/views/assets.xml
Labels: bot is merging ⏳

#626 [14.0] [FIX] auth_jwt: Unhandled PyJWKClientError in _get_key
  auth_jwt/models/auth_jwt_validator.py
Labels: bot is merging ⏳

#544 [16.0][MIG] auth_api_key_group
  auth_api_key_group/README.rst
  auth_api_key_group/__init__.py
  auth_api_key_group/__manifest__.py
  auth_api_key_group/i18n/auth_api_key_group.pot
  auth_api_key_group/models/__init__.py
  auth_api_key_group/models/auth_api_key.py
  auth_api_key_group/models/auth_api_key_group.py
  auth_api_key_group/readme/CONTRIBUTORS.rst
  auth_api_key_group/readme/DESCRIPTION.rst
  auth_api_key_group/security/ir.model.access.csv
  auth_api_key_group/static/description/icon.png
  auth_api_key_group/static/description/index.html
  auth_api_key_group/tests/__init__.py
  auth_api_key_group/tests/test_auth_api_key_group.py
  auth_api_key_group/views/auth_api_key_group_view.xml
  auth_api_key_group/views/auth_api_key_view.xml
  setup/auth_api_key_group/odoo/addons/auth_api_key_group
  setup/auth_api_key_group/setup.py
Labels: approved, bot is merging ⏳

#613 [IMP][14.0] auth_saml: download the provider metadata
  auth_saml/README.rst
  auth_saml/models/auth_saml_provider.py
  auth_saml/readme/CONFIGURE.rst
  auth_saml/tests/data/cert_idp_expired.pem
  auth_saml/tests/data/key_idp_expired.pem
  auth_saml/tests/fake_idp.py
  auth_saml/tests/test_pysaml.py
  auth_saml/views/auth_saml.xml
Labels: approved, bot is merging ⏳

#620 [17.0][MIG] auth_oidc
  auth_oidc/README.rst
  auth_oidc/__init__.py
  auth_oidc/__manifest__.py
  auth_oidc/controllers/__init__.py
  auth_oidc/controllers/main.py
  auth_oidc/data/auth_oauth_data.xml
  auth_oidc/demo/local_keycloak.xml
  auth_oidc/i18n/auth_oidc.pot
  auth_oidc/i18n/es.po
  auth_oidc/i18n/it.po
  auth_oidc/models/__init__.py
  auth_oidc/models/auth_oauth_provider.py
  auth_oidc/models/res_users.py
  auth_oidc/pyproject.toml
  auth_oidc/readme/CONFIGURE.md
  auth_oidc/readme/CONTRIBUTORS.md
  auth_oidc/readme/DESCRIPTION.md
  auth_oidc/readme/HISTORY.md
  auth_oidc/readme/INSTALL.md
  auth_oidc/readme/ROADMAP.md
  auth_oidc/readme/USAGE.md
  auth_oidc/static/description/icon.png
  auth_oidc/static/description/index.html
  auth_oidc/static/description/oauth-microsoft_azure-api_permissions.png
  auth_oidc/static/description/oauth-microsoft_azure-optional_claims.png
  auth_oidc/static/description/odoo-azure_ad_multitenant.png
  auth_oidc/tests/__init__.py
  auth_oidc/tests/keycloak/keycloak-config.json
  auth_oidc/tests/keycloak/keycloak.sh
  auth_oidc/tests/test_auth_oidc_auth_code.py
  auth_oidc/views/auth_oauth_provider.xml
  requirements.txt
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳
