Repository OCA/server-auth, pull requests merged in 2025-03, with the labels that each got.

#736 [17.0] auth_session_timeout: Fix pre-migrate script
  auth_session_timeout/migrations/17.0.1.0.0/pre-migration.py
Labels: bug, bot is merging ⏳

#715 [18.0][MIG] auth_session_timeout
  auth_session_timeout/README.rst
  auth_session_timeout/__init__.py
  auth_session_timeout/__manifest__.py
  auth_session_timeout/data/ir_config_parameter_data.xml
  auth_session_timeout/i18n/ar.po
  auth_session_timeout/i18n/auth_session_timeout.pot
  auth_session_timeout/i18n/ca.po
  auth_session_timeout/i18n/da.po
  auth_session_timeout/i18n/de.po
  auth_session_timeout/i18n/el_GR.po
  auth_session_timeout/i18n/es.po
  auth_session_timeout/i18n/es_ES.po
  auth_session_timeout/i18n/fi.po
  auth_session_timeout/i18n/fr.po
  auth_session_timeout/i18n/fr_CH.po
  auth_session_timeout/i18n/fr_FR.po
  auth_session_timeout/i18n/hr.po
  auth_session_timeout/i18n/hr_HR.po
  auth_session_timeout/i18n/it.po
  auth_session_timeout/i18n/nl.po
  auth_session_timeout/i18n/nl_NL.po
  auth_session_timeout/i18n/pt.po
  auth_session_timeout/i18n/pt_BR.po
  auth_session_timeout/i18n/ro.po
  auth_session_timeout/i18n/sl.po
  auth_session_timeout/i18n/tr.po
  auth_session_timeout/i18n/tr_TR.po
  auth_session_timeout/i18n/zh_CN.po
  auth_session_timeout/models/__init__.py
  auth_session_timeout/models/ir_config_parameter.py
  auth_session_timeout/models/ir_http.py
  auth_session_timeout/models/res_users.py
  auth_session_timeout/pyproject.toml
  auth_session_timeout/readme/CONFIGURE.md
  auth_session_timeout/readme/CONTRIBUTORS.md
  auth_session_timeout/readme/DESCRIPTION.md
  auth_session_timeout/readme/USAGE.md
  auth_session_timeout/static/description/icon.png
  auth_session_timeout/static/description/index.html
  auth_session_timeout/tests/__init__.py
  auth_session_timeout/tests/test_ir_config_parameter.py
  auth_session_timeout/tests/test_res_users.py
Labels: approved, bot is merging ⏳

#769 [16.0][IMP] auth_api_key_server_env: refresh warning
  auth_api_key_server_env/tests/test_auth_api_key.py
Labels: bot is merging ⏳

#762 [16.0][FIX] password_security: Fix expected singleton
  password_security/models/res_users.py
  password_security/tests/test_change_password.py
Labels: bot is merging ⏳

#713 [16.0][FIX] password_security: update password_write_date on copy
  password_security/controllers/main.py
  password_security/models/res_users.py
  password_security/tests/test_signup.py
Labels: approved, ready to merge, bot is merging ⏳
