Repository OCA/server-auth, pull requests merged in 2025-04, with the labels that each got.

#734 [16.0] [ADD] cross_connect_server
  cross_connect_server/README.rst
  cross_connect_server/__init__.py
  cross_connect_server/__manifest__.py
  cross_connect_server/dependencies.py
  cross_connect_server/models/__init__.py
  cross_connect_server/models/cross_connect_client.py
  cross_connect_server/models/fastapi_endpoint.py
  cross_connect_server/models/res_users.py
  cross_connect_server/readme/CONTRIBUTORS.md
  cross_connect_server/readme/DESCRIPTION.md
  cross_connect_server/readme/USAGE.md
  cross_connect_server/routers/__init__.py
  cross_connect_server/routers/cross_connect.py
  cross_connect_server/schemas.py
  cross_connect_server/security/ir_model_access.xml
  cross_connect_server/security/res_groups.xml
  cross_connect_server/static/description/index.html
  cross_connect_server/tests/__init__.py
  cross_connect_server/tests/test_cross_connect_server.py
  cross_connect_server/views/fastapi_endpoint_views.xml
  setup/cross_connect_server/odoo/addons/cross_connect_server
  setup/cross_connect_server/setup.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#733 [16.0][FIX] users_ldap_populate: get additional operational attributes
  users_ldap_populate/models/users_ldap.py
Labels: approved, bot is merging ⏳

#784 [18.0][MIG] impersonate_login: migration to V18
  impersonate_login/README.rst
  impersonate_login/__init__.py
  impersonate_login/__manifest__.py
  impersonate_login/hooks.py
  impersonate_login/i18n/impersonate_login.pot
  impersonate_login/i18n/it.po
  impersonate_login/models/__init__.py
  impersonate_login/models/impersonate_log.py
  impersonate_login/models/ir_http.py
  impersonate_login/models/mail_message.py
  impersonate_login/models/mail_thread.py
  impersonate_login/models/model.py
  impersonate_login/models/res_users.py
  impersonate_login/pyproject.toml
  impersonate_login/readme/CONFIGURE.md
  impersonate_login/readme/CONTRIBUTORS.md
  impersonate_login/readme/DESCRIPTION.md
  impersonate_login/readme/USAGE.md
  impersonate_login/security/group.xml
  impersonate_login/security/ir.model.access.csv
  impersonate_login/static/description/icon.png
  impersonate_login/static/description/index.html
  impersonate_login/static/src/js/user_menu.esm.js
  impersonate_login/tests/__init__.py
  impersonate_login/tests/test_impersonate_login.py
  impersonate_login/views/impersonate_log.xml
  impersonate_login/views/res_users.xml
Labels: bot is merging ⏳

#786 [18.0][FIX] auth_saml: fix getting uid from authenticate return value
  auth_saml/controllers/main.py
  auth_saml/tests/test_pysaml.py
Labels: approved, bot is merging ⏳

#785 [18.0][MIG] auth_user_case_insensitive
  auth_user_case_insensitive/README.rst
  auth_user_case_insensitive/__init__.py
  auth_user_case_insensitive/__manifest__.py
  auth_user_case_insensitive/hooks.py
  auth_user_case_insensitive/i18n/ar.po
  auth_user_case_insensitive/i18n/auth_user_case_insensitive.pot
  auth_user_case_insensitive/i18n/ca.po
  auth_user_case_insensitive/i18n/da.po
  auth_user_case_insensitive/i18n/de.po
  auth_user_case_insensitive/i18n/el_GR.po
  auth_user_case_insensitive/i18n/es.po
  auth_user_case_insensitive/i18n/es_ES.po
  auth_user_case_insensitive/i18n/fi.po
  auth_user_case_insensitive/i18n/fr.po
  auth_user_case_insensitive/i18n/fr_CH.po
  auth_user_case_insensitive/i18n/fr_FR.po
  auth_user_case_insensitive/i18n/hr.po
  auth_user_case_insensitive/i18n/hr_HR.po
  auth_user_case_insensitive/i18n/it.po
  auth_user_case_insensitive/i18n/lt.po
  auth_user_case_insensitive/i18n/nl.po
  auth_user_case_insensitive/i18n/nl_NL.po
  auth_user_case_insensitive/i18n/pt.po
  auth_user_case_insensitive/i18n/pt_BR.po
  auth_user_case_insensitive/i18n/ro.po
  auth_user_case_insensitive/i18n/sl.po
  auth_user_case_insensitive/i18n/tr.po
  auth_user_case_insensitive/i18n/tr_TR.po
  auth_user_case_insensitive/i18n/zh_CN.po
  auth_user_case_insensitive/models/__init__.py
  auth_user_case_insensitive/models/res_users.py
  auth_user_case_insensitive/pyproject.toml
  auth_user_case_insensitive/readme/CONTRIBUTORS.md
  auth_user_case_insensitive/readme/DESCRIPTION.md
  auth_user_case_insensitive/readme/INSTALL.md
  auth_user_case_insensitive/readme/USAGE.md
  auth_user_case_insensitive/static/description/icon.png
  auth_user_case_insensitive/static/description/index.html
  auth_user_case_insensitive/tests/__init__.py
  auth_user_case_insensitive/tests/test_res_users.py
Labels: approved, bot is merging ⏳

#754 [18.0][MIG] auth_oauth_multi_token: Migration to 18.0
  auth_oauth_multi_token/README.rst
  auth_oauth_multi_token/__init__.py
  auth_oauth_multi_token/__manifest__.py
  auth_oauth_multi_token/i18n/auth_oauth_multi_token.pot
  auth_oauth_multi_token/i18n/it.po
  auth_oauth_multi_token/models/__init__.py
  auth_oauth_multi_token/models/auth_oauth_multi_token.py
  auth_oauth_multi_token/models/res_users.py
  auth_oauth_multi_token/pyproject.toml
  auth_oauth_multi_token/readme/CONFIGURATION.rst
  auth_oauth_multi_token/readme/CONTRIBUTORS.md
  auth_oauth_multi_token/readme/DESCRIPTION.md
  auth_oauth_multi_token/readme/USAGE.md
  auth_oauth_multi_token/security/ir.model.access.csv
  auth_oauth_multi_token/static/description/icon.png
  auth_oauth_multi_token/static/description/index.html
  auth_oauth_multi_token/tests/__init__.py
  auth_oauth_multi_token/tests/test_multi_token.py
  auth_oauth_multi_token/views/auth_oauth_multi_token.xml
  auth_oauth_multi_token/views/res_users.xml
Labels: approved, ready to merge, bot is merging ⏳
