Repository OCA/server-auth, pull requests merged in 2025-06, with the labels that each got.

#800 [16][cross_connect_server]No invitation email for cross server created user
  cross_connect_server/models/cross_connect_client.py
Labels: approved, bot is merging ⏳

#735 [16.0] [ADD] cross_connect_client
  cross_connect_client/README.rst
  cross_connect_client/__init__.py
  cross_connect_client/__manifest__.py
  cross_connect_client/controllers/__init__.py
  cross_connect_client/controllers/cross_connect.py
  cross_connect_client/models/__init__.py
  cross_connect_client/models/cross_connect_server.py
  cross_connect_client/models/res_groups.py
  cross_connect_client/readme/CONTRIBUTORS.md
  cross_connect_client/readme/DESCRIPTION.md
  cross_connect_client/readme/USAGE.md
  cross_connect_client/security/ir_model_access.xml
  cross_connect_client/static/description/index.html
  cross_connect_client/static/description/web_icon_data.png
  cross_connect_client/tests/__init__.py
  cross_connect_client/tests/test_cross_connect_client.py
  cross_connect_client/views/cross_connect_server_views.xml
  setup/cross_connect_client/odoo/addons/cross_connect_client
  setup/cross_connect_client/setup.py
Labels: approved, bot is merging ⏳

#727 [18.0][MIG] auth_signup_verify_email: Migration to 18.0
  auth_signup_verify_email/README.rst
  auth_signup_verify_email/__init__.py
  auth_signup_verify_email/__manifest__.py
  auth_signup_verify_email/controllers/__init__.py
  auth_signup_verify_email/controllers/main.py
  auth_signup_verify_email/i18n/ar.po
  auth_signup_verify_email/i18n/auth_signup_verify_email.pot
  auth_signup_verify_email/i18n/de.po
  auth_signup_verify_email/i18n/es.po
  auth_signup_verify_email/i18n/fi.po
  auth_signup_verify_email/i18n/fr.po
  auth_signup_verify_email/i18n/hr.po
  auth_signup_verify_email/i18n/hr_HR.po
  auth_signup_verify_email/i18n/it.po
  auth_signup_verify_email/i18n/pt_BR.po
  auth_signup_verify_email/i18n/ro.po
  auth_signup_verify_email/i18n/sl.po
  auth_signup_verify_email/i18n/tr.po
  auth_signup_verify_email/pyproject.toml
  auth_signup_verify_email/readme/CONFIGURE.md
  auth_signup_verify_email/readme/CONTRIBUTORS.md
  auth_signup_verify_email/readme/DESCRIPTION.md
  auth_signup_verify_email/readme/INSTALL.md
  auth_signup_verify_email/readme/USAGE.md
  auth_signup_verify_email/static/description/icon.png
  auth_signup_verify_email/static/description/icon.svg
  auth_signup_verify_email/static/description/index.html
  auth_signup_verify_email/tests/__init__.py
  auth_signup_verify_email/tests/test_verify_email.py
  auth_signup_verify_email/views/signup.xml
  requirements.txt
Labels: approved, bot is merging ⏳

#658 [MIG] auth_oauth_autologin: Migration to 17.0
  auth_oauth_autologin/README.rst
  auth_oauth_autologin/__init__.py
  auth_oauth_autologin/__manifest__.py
  auth_oauth_autologin/controllers/__init__.py
  auth_oauth_autologin/controllers/main.py
  auth_oauth_autologin/i18n/auth_oauth_autologin.pot
  auth_oauth_autologin/models/__init__.py
  auth_oauth_autologin/models/auth_oauth_provider.py
  auth_oauth_autologin/pyproject.toml
  auth_oauth_autologin/readme/CONFIGURE.md
  auth_oauth_autologin/readme/DESCRIPTION.md
  auth_oauth_autologin/readme/USAGE.md
  auth_oauth_autologin/static/description/icon.png
  auth_oauth_autologin/static/description/index.html
  auth_oauth_autologin/static/src/js/web_login.esm.js
  auth_oauth_autologin/views/assets.xml
  auth_oauth_autologin/views/auth_oauth_provider.xml
Labels: approved, bot is merging ⏳

#764 [17.0][IMP] auth_oauth_multi_token: make it compatible with odoo.sh "login as"
  auth_oauth_multi_token/README.rst
  auth_oauth_multi_token/__manifest__.py
  auth_oauth_multi_token/migrations/17.0.1.1.0/pre-migration.py
  auth_oauth_multi_token/models/auth_oauth_multi_token.py
  auth_oauth_multi_token/models/res_users.py
  auth_oauth_multi_token/readme/CONFIGURATION.md
  auth_oauth_multi_token/readme/CONTRIBUTORS.md
  auth_oauth_multi_token/static/description/index.html
  auth_oauth_multi_token/tests/test_multi_token.py
Labels: approved, ready to merge, bot is merging ⏳

#805 [17.0][FIX] auth_api_key: Use 401 for unauthorized user
  auth_api_key/models/ir_http.py
Labels: bot is merging ⏳

#806 [18.0][FIX] auth_api_key: Use 401 for unauthorized user
  auth_api_key/models/ir_http.py
Labels: bot is merging ⏳

#808 [18.0][IMP] auth_oauth_multi_token: make it compatible with odoo.sh "login as"
  auth_oauth_multi_token/README.rst
  auth_oauth_multi_token/models/auth_oauth_multi_token.py
  auth_oauth_multi_token/models/res_users.py
  auth_oauth_multi_token/readme/CONFIGURATION.md
  auth_oauth_multi_token/readme/CONTRIBUTORS.md
  auth_oauth_multi_token/static/description/index.html
  auth_oauth_multi_token/tests/test_multi_token.py
Labels: approved, ready to merge, bot is merging ⏳
